### ISSUE TITLE
Comments on 522x1r3_final_post_review_update

### ISSUE THREAD

**Issue by PjrWilson** [SamCooper/MC_SPEC_RIDS#1]
2.4.3 Action Provider Addressing

Problem: 
last para:
"In relative addressing, this is when the address used ..."

Suggestion:
Unnecessary words. Remove "this is when"

2.11 Group Service

Problem:
"The objects linked to must all be of the same type, the group structure restricts this, and in the same domain"

Suggestion:
Doesn't read very well - replace , with - or (

Section 3.2.1 General

Problem:
"The action is then executed in the provider which can **be** also be monitored using the activity tracking pattern"

Suggestion:
Remove first be (**be** above)

Problem:
"There may be required coordination between action service consumers to ensure the action object instance identifiers are unique, how this is done is outside the scope of this specification however a good approach is the use of a central COM archive as that can provide the unique instance identifiers."

Suggestion:
Change start of sentence to 
"Coordination may be required between..."
Also, should be 2 sentences - change "unique, how this is..."  to "unique. How this is..."

Section 3.2.2 

Problem:
points e & f talk about updating/removing the "definition of a definition". 

Query:
Shouldn't this just be update/remove the definition itself.
(Definition of a definition is a bit meta...)

3.2.4 COM Usage

Problem:
e) - the precise meaning of this is slightly unclear. Read a certain way, it could be read that ActionDefinitions should be dynamic things.

Suggestion:
It may be as simple as the place in this requirement list. a) talks about the definition, subsequent entries talk about the instance (ie dynamic things).
If e) was moved to b), it would be a start.

3.4.7.2 Structures

Problem:
e) The service provide shall...  

Suggestion:
"provide" should be "provider"
There are other occurrences - search for "The service provide " (I get 5).

**Comment by SamCooper** [comment]
Fixed
