### ISSUE TITLE
Evaluating Expressions (M&C and COM)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#100]
There's an operation that should be defined in some helper which allows the MO programmer to easily compare 2 attribute values.

The type signature must be the following:
public static Boolean evaluateExpression(Attribute leftHandSide, ExpressionOperator operator, Attribute rightHandSide);

Usages:
Archive service when filtering on a certain field is enabled.
Conversion service during the evaluation of a Parameter Expression.
Conversion service during the comparisons to find the maximum and minimum points surrounding a certain value.
Parameter service during the evaluation of a Parameter Expression.

At the current moment, the standard does not specify the details of this operation. This implies that if 2 different people do 2 different implementations, their understanding of how this evaluation should be done might be different, resulting in 2 different outputs for the same service with the exact same configuration.

My major concern is the comparison of 2 different Attribute types. For example, can I compare a String with an Identifier? The answer can be yes or no. 
Yes, because in the end they are both strings. No, because they are of 2 different types (String vs Identifier).
The same applies to Double and Float, for example.

For example, in my implementation of this method, I allow comparing different types. This is done by converting everything to either double or string, and then comparing them. (String if shortFormPart is 6, 15 or 18; otherwise Double). Although, I have the feeling that this might be too complex and that it should simply reject in case they have different types.

Honestly, it would be better to have this operation already implemented in order to avoid different interpretations of this operation. I can provide my already implemented method if you are interested.
# 100MCRIDsAchieved  :D

**Comment by SamCooper** [comment]
I'm not sure if this is a RID on the specification or not?
