### ISSUE TITLE
Action Service: submitAction operation

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#101]
1.
The submitAction operation does not include a requirement saying something like:
"If an error is returned, no action shall be executed."

2.
The submitAction contains an UNKNOWN error "Submitted action definition is unknown." but in the requirements it is not explicitly stated that this error must be return if the actionDefinition does not exist.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
