### ISSUE TITLE
Book Formatting: numbering of requirements

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#102]
Please revert the numbering of the requirements to the old style.

Example, previously it was: 3.3.5.2.1

Now we have just: c

This makes life much harder when one is looking for a specific requirement,  because "c" does not uniquely identify the requirement and therefore one cannot use the "find" operation in the pdf to quickly get the exact requirement we are looking for.

I believe that I raised this issue before on the previous book iteration (from October 2014) but it was not fixed in the March 2015th version. Please fix this.

**Comment by SamCooper** [comment]
I have to modify the generator to do this which is not so easy. Tom Gannet fixes this in the release version.

I have opened this issue in the Stub generator though.

**Comment by CesarCoelho** [comment]
The  latest version of the M&C book has this fixed. Please close the thread.
