### ISSUE TITLE
Alert service: Requirement 3.4.8.2.c

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#104]
"c) The enableInstance field shall support the wildcard value of '0' and matches all AlertDefinition objects of the provider"

The requirement is not accurate because the enableInstance field is type COM::InstanceBooleanPair.
Perhaps:
"c) The id field of the enableInstance object shall support the wildcard value of '0' and matches all AlertDefinition objects of the provider"

And even for this case, you must include as well that it does not apply to groups!

Please also review the equivalent requirements from other services:
3.3.10.2.c
3.4.8.2.c
3.6.12.2.c
3.7.9.2.c

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Done, I didn't make any special case for groups though as it still applies i.e. with a wildcard in that field it matches all relevant objects (AlertDefinition etc) regardless of whether you are using groups or not.
