### ISSUE TITLE
Alert Service: argumentIds field of the AlertDefinitionDetails

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#105]
The argumentIds list from the AlertDefinitionDetails structure contains the following description:
"
Optional list of argument definition identifiers. Allows the provider to verify that the correct arguments are being supplied.
"

Change it to include the meaning of being null, something like:
"
Optional list of argument definition identifiers. Allows the provider to verify that the correct arguments are being supplied. If null, the argument definition identifiers are not checked before the emission of an Alert Event.
"

You also need to include a requirement in the "Functional requirements" section of the Alert service stating that: the supplied argumentIds must be verified against the ones in the Definition before an Alert emission. If the argumentIds field from the definition is null, then no verification shall take place.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
