### ISSUE TITLE
Statistic Service: updateParameterEvaluation (requirement missing)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#106]
In the updateParameterEvaluation operation of the Statistic service there's one requirement missing.

It should state that if the sampling interval is updated, then the service shall sample with the new rate immediately.
Otherwise it leaves open to the implementer to decide.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
