### ISSUE TITLE
Statistic Service: enableService operation & getServiceStatus operation

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#107]
Please remove the enableService and getServiceStatus operations from the Statistic service.
The PUS Statistic service doesn't allow the complete service disabling like the PUS On-board monitoring (equivalent check service).

**Important**: Please leave the **enableService** and **getServiceStatus** operation of the **Check service** as this one is for PUS compliance.

**Comment by SamCooper** [comment]
We added those so that the services were balanced.
