### ISSUE TITLE
Statistic service: getStatistics operation

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#108]
The entry point to get a statistic evaluation is the statistic link.
Currently, the getStatistics operation is requesting the objId of the parameter and the objId of the statistic function.

With the current model, we cannot provide the Statistics right away because, for example, for a Mean average, one needs x time, and therefore it cannot be provided instantaneously. 

1.
My suggestion would be the inputs of this operation to the statistic link objId. 
Yes, I could try to match the objId of the Statistic function AND objId of the Parameter with a certain statistic link and provide the result, but if the generation of this statistic evaluation is off, it is impossible to provide a value without x time to evaluate it. 

2.
Please add an error in case no statistic link is matched.

3.
Please add an error in case the evaluation is inactive.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I have included an extra requirement to cover the situation where it is not possible to determine the evaluation result. No error should be returned though as it is a search operation rather than one that should fail.
