### ISSUE TITLE
Parameter service: change updateInterval to reportingInterval (suggestion)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#109]
Suggestion for improvement:
Change the keyword "update" (as in updateInterval), to "reporting" (would become reportingInterval).

Reasons:
1. The word "report" is more appropriate
2. The "Update" keyword is already used in the interaction patterns
3. Would become consistent with the Statistic service terminology (reporting is used there)

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
