### ISSUE TITLE
Statistic service: Maximum and Minimum not clear

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#111]
Let's consider the following example for the Maximum statistic function:

we have a set of 5 discrete values from 0 to 5
And we get the following series of parameter values:

time A: 3
time B: 5
time C: 2
time D: 5
time E: 3

On the StatisticEvaluationReport for the Maximum value, which time should be stamped?
It is clear that the maximum value was 5. But what about the time? time B or time D?

The question is should it be the time of the first maximum or the last maximum value?
Please clarify this in the standard, both for Maximum and Minimum.

**Comment by SamCooper** [comment]
Accepted

**Comment by CesarCoelho** [comment]
We will choose the first one.

**Comment by SamCooper** [comment]
Done
