### ISSUE TITLE
Statistic service: Mean statistic function

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#112]
For discrete parameter values (e.g. Integers), the mean should be presented as double.

Consider the following situation:
the received set of values are: 3, 3, 3, 4, 4, 4
The mean should be 3.5
But if the StatisticEvaluationReport value value follows the original type, then we will get a 4, which does not represent a good value of the mean value.

**Comment by CesarCoelho** [comment]
WG review:

Accepted

**Comment by SamCooper** [comment]
Done
