### ISSUE TITLE
Parameter service: setValue operation (support for setting multiple parameters with groups)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#114]
Change the setValue operation to support the setting of multiple parameters through the use of a group.
Add a new field to the setValue operation:
isGroupId : (MAL::Boolean)

Add a requirement stating that the values get set together i.e. requiring some sort of locking in the implementation.
And additional requirements stating that if the first flag is true, then the paramDefInstId is a object instance identifier of a group. 
It will also need some additional errors such as: "a)        The supplied group is not a group of groups nor a group of ParameterDefinition objects."

**Comment by SamCooper** [comment]
So I would set all parameters in the group to the same value?

**Comment by CesarCoelho** [comment]
This RID comes from the SAVOIR-SOIS study. The idea was to set multiple parameters at the exact same time, not all to the same value.

**Comment by CesarCoelho** [comment]
WG review:

The request to add in locking and concurrency constraints is accepted. The wording and operation specification will be updated to reflect this.

**Comment by SamCooper** [comment]
Done.
