### ISSUE TITLE
Statistic service: listParameterEvaluations ()  ?

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#116]
In the Statistic service there is no way of checking which statistic links are available in the provider.
Please add a listParameterEvaluation() operation to the service.

**Comment by SamCooper** [comment]
Accepted

**Comment by CesarCoelho** [comment]
This is not an "enhancement", it's a BUG. Please label it correctly

**Comment by SamCooper** [comment]
This operation should return the actual link objects so that you can determine the reporting state of the link.

**Comment by SamCooper** [comment]
Done
