### ISSUE TITLE
Statistic service: Statistic Functions mathematically defined in the standard

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#117]
The calculation for the Statistic functions is not explicitly documented in the standard.
For example, the maximum should be based on a "a < b" comparison or on a "a <= b" comparison?

Please explicitly define (mathematically) how the calculation of the statistic function should be performed for the 4 default functions.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
