### ISSUE TITLE
Aggregation service: Allow custom categories & publish them

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#118]
I have been talking with Maya (in cc) and she told me that in the future she would like to filter published Aggregations by category for the MOE METERON infrastructure. 
For this, the changes proposed would be 3: 
1.
I was checking the monitorValue operation and the fourth entity key is not being used: "d) The MAL EntityKey.fourthSubKey shall be NULL" 
Maybe we could use this field to transmit the category of the aggregation. 
So:
"d) The MAL EntityKey.fourthSubKey shall be the category of the aggregation." 

2.
Change the category field of the of the Aggregation to allow custom categories like it was done for the Parameter validity. 
This would mean a change in the category field from AggregationCategory type to MAL::UOctet. 

3.
Add requirements for the custom categories:
x)  //Define the Aggregation category GENERAL as '1'
y)  //Define the Aggregation category DIAGNOSTIC as '2'
z)  It is supported that other, deployment specific, category values be used however the meaning of those values is deployment specific and outside the scope of this standard. They must use values greater than 127.

---

Please don't remove the AggregationCategory enumeration so it can still be used by the implementations.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done except for part 1 as the 4th key is now used.
