### ISSUE TITLE
Changes permitted by the updateDefinition of the Action service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#12]
Could the severity field of the ActionDefinition not be modified by the updateDefinition operation ?

**Comment by SamCooper** [comment]
No. This is because it would mean that looking back in history the severity that was in place at the time would not match what the definition states it is.

Anything that changes the nature of the command is not permitted by the updateXXX operations.

If you agree please close the RID.

**Comment by SamCooper** [comment]
Done.
