### ISSUE TITLE
Alert service: AlertEventDetails structure

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#120]
Consider changing the argumentValues field to attributeValues field and change the type to List< AttributeValue >

The only difference in the change is that the AttributeValue structure does not include the isConvertedValue field available in the ArgumentValue structure.
For the case of Alerts, this field seems redundant.

**Comment by CesarCoelho** [comment]
Agreed

**Comment by SamCooper** [comment]
Done.
