### ISSUE TITLE
Check service: Check Links available

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#122]
Currently it is not possible to list which Check links are available in the Provider.

Please add a listParameterCheck() operation to retrieve all the available object instance identifiers of the check links in the provider.
No need for input arguments because the Check links don't have an identifier, just return all.

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
This operation should return the actual link objects so that you can determine the reporting state of the link.

**Comment by SamCooper** [comment]
Done.
