### ISSUE TITLE
Check service: Limit check and Delta check

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#123]
It is not clear if during the comparison process the boundary is imcluded or not.
In practical terms, are the comparisons "greater and equal", "less and equal" or just "greater", "less".
I am assuming the second case but please make it clear in the standard to avoid misinterpretations of the checks.

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
These are actually covered in the high level requirements, for example:

d)  When performing a limit check, the check service shall:
a.  check that the value of a parameter lies within a pair of limit values if set to violate in range, or outside a pair of limits if set to violate outside the range;

I.e. boundary in not included in the valid part.

Is this OK?

**Comment by CesarCoelho** [comment]
Just checked. I think the problem is with the word "within".  Does it mean with or without borders? I am assuming with but just because the sentence after says "outside". 
Maybe it can be clarified by adding a simple sentence after.

**Comment by SamCooper** [comment]
Ok.

**Comment by SamCooper** [comment]
Changed to:

d) When performing a limit check, the check service shall:
a. check that the value of a parameter lies within **or on** a pair of limit values if set to violate in range, or outside a pair of limits if set to violate outside the range;

Same for delta
