### ISSUE TITLE
Check service: Percentage delta threshold requirement

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#124]
"z) For percentage based delta thresholds, the percentage is calculated as the arithmetic difference between the reference value and the parameter value, as a percentage of the first valid sample where the result of the calculation equal to 1.0 is interpreted as 100 per cent. For example, if the reference value is 8 and the parameter value is 14 then the calculation is (14 - 8) / 8 or 0.75 or 75%."

Can we change it to:

"z) For percentage based delta thresholds, the calculation of the percentage is given by the absolute value of the difference between the parameter value and reference value divided by the reference value. The result of a calculation that equals to 1.0 shall be interpreted as 100 per cent. For example, if the reference value is 8 and the parameter value is 14 then the calculation is |14 - 8| /  8, which is evaluated as 0.75 or 75%."

Please notice that I changed the brackets by pipes to represent the module of the difference.

**Comment by SamCooper** [comment]
I don't understand the phrase "module of the difference"?

**Comment by CesarCoelho** [comment]
updated!

**Comment by CesarCoelho** [comment]
WG review:

Using absolute value is not a good idea, however the algo should be made clear that it supports +/- deltas.

**Comment by SamCooper** [comment]
Done.
