### ISSUE TITLE
Check service: CheckLink "no identity" problems

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#127]
From the enableCheck operation:
"j) The provider should create and store a new CheckLink object in the COM archive if the checkEnabled field is changed."

This causes problems because the check links keep changing their own object instance identifier. So, a simple enable/disable would cause 1 new object in the Archive, and a different object instance identifier for that check link in the service. From ground, the previous object instance identifier, would no longer be valid/reachable and therefore the check link can no longer be enabled.

The CheckLink would need an equivalent "identity" object like the definitions have.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Related to #179

**Comment by NicolasVorwerg** [comment]
There is the same issue with the StatisticLink-Object at the Statistic Service. Please also add a StatisticLinkIdentity-Object to solve the problem.

**Comment by SamCooper** [comment]
Done
