### ISSUE TITLE
Action service: ActionDefinitionDetails structure

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#129]
The Action service is a generic service to execute actions.
In this context, many times an action doesn't really have a "severity" associated with it because it is just "an action".
Examples: TurnLeft, takePicture, enableCamera (None of the severities really fit: INFORMATIONAL/WARNING/ALARM/SEVERE/CRITICAL)
I don't think that there should be a "severity" field associated with an action.

Therefore, I would suggest the replacement of the severity field in the ActionDefinitionDetails by a category field, as this can be way more useful to a consumer. This would allow him/her to categorize his/her actions based on implementation-specific choices.
FROM: severity (Severtiy)
TO: category (UInteger and nullable)

A default category enumeration could be created and added in the book but it is not necessary.

**Comment by SamCooper** [comment]
Agreed.

**Comment by SamCooper** [comment]
Done.
