### ISSUE TITLE
Flow chart for determining the validity of a parameter

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#13]
The flow chart describing the calculation of the validity of a parameter in section 3.3.1 is not completely coherent with statement l) of section 3.3.3:
l)  If the validityExpression field is NULL, or the validity expression evaluates to TRUE, and the conversion of the parameter value fails (for example an unexpected value for a discrete conversion), then the validity state shall be INVALID_CONVERSION by setting the ParameterValue isValid field to FALSE and the invalidSubState field to '3'.

As it is now, when the validityExpression field is NULL, the flow chart shows that the validity is always VALID and the result of the conversion is not taken into account.

It should be modified to reflect correctly the text, as shown in the attached file.
![validity_conditions](https://cloud.githubusercontent.com/assets/9323968/4824486/d724cf4e-5f5a-11e4-8b0c-60f8bf5d1a70.JPG)

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
