### ISSUE TITLE
Severity Enumeration

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#130]
Severity has different meaning in different countries/cultures.
This causes ambiguities in the interpretation of an Alert depending on the reader.
Please consider adding a rating number on all severities to avoid ambiguities.

From:
INFORMATIONAL
WARNING
ALARM
SEVERE
CRITICAL

To:
INFORMATIONAL_RATE_0
WARNING_RATE_1
ALARM_RATE_2
SEVERE_RATE_3
CRITICAL_RATE_4

If you don't like the word "RATE" please feel free to suggest something different.

**Comment by SamCooper** [comment]
I think the text associated with the enumeration should make it clear the ordering but I won't put a number into the text.

**Comment by SamCooper** [comment]
Done.
