### ISSUE TITLE
ParameterExpression-object - definition id correct?

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#132]
The parameterId field of the Composite: ParameterExpression is described in its comment-column to: 

"identify the parameter definition to be used in the expression." 

Is it right to be the id of the Parameter defintions? Or is it a leftover from a previous specification and it should be the id of the parameteridentity? 

Please check which one is right.

**Comment by NicolasVorwerg** [comment]
see parent RID: #179

**Comment by SamCooper** [comment]
Changed to ParameterIdentity
