### ISSUE TITLE
ParameterService: enableGeneration operation - error incomplete

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#134]
The requirement 3.3.10.3.1a about the unknown-error says: 
"One or more of the requested parameters is unknown."

Please also add that an unknown error shall be returned for unknown groups. So please change it to : 
"One or more of the requested parameters or groups is unknown."

There is the same issue at the one of the other services that provide the enableGeneration-Operation: AggregationsService.

**Comment by NicolasVorwerg** [comment]
Furthermore there is the same issue at the enableFilter-operation at the AggregationService.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
