### ISSUE TITLE
All Services: enableGeneration operation using groups

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#135]
The requirements 3.3.10.2.a,g and h are mentioning "Group object instance identifiers" that should be referenced for enableing the generation of its objects. Please specify if the identifiers must be GroupIdentity object instance identifiers or GroupDefinition object instance identifiers.

Taking in account the COM-Usage requirements of the GroupService 3.9.4.g,h. saying: "[Other service objects and Groups]  shall reference instances of a group using the object instance identifier of the GroupDefinition." it should be the GroupDefinition object instance identifiers.

There is the same issue at the other services that provide the enableGeneration-Operation: AggregationsService, AlertService.

**Comment by NicolasVorwerg** [comment]
Furthermore there is the same issue at the enableFilter-operation at the AggregationService.

**Comment by NicolasVorwerg** [comment]
As well as at the enableCheck-operation at the CheckService.

**Comment by NicolasVorwerg** [comment]
also see RID: #179

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I've clarified the requirements in the group service and also added a short paragraph to the description of the group service stating that other services always reference GroupIdentity objects.
I've also clarified in the other service operations that they should reference GroupIdentity objects
