### ISSUE TITLE
ParameterService: addDefintion and updateDefinition - error missing

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#136]
The functional requirement 3.3.3.h says: "If an interval that is not supported by the provider is requested, then an INVALID error shall be returned, and the change rejected.

You can set an interval during the addDefintion- and updateDefinition-Operation. Thus there should also be a sentence in the INVALID-Error-sections of the addDefintion and updateDefinition-Operation that says that an INVALID Error shall be thrown if the interval is not supported. 

Please add these extra sentences in the error-sections.

**Comment by NicolasVorwerg** [comment]
There is the same issue at the addDefiinition and updateDefinition-operation at the AggregationService.

**Comment by NicolasVorwerg** [comment]
Same issue at the CheckService. E.g. if setting an invalid interval or if nominal/violation count/time have invalid combinations.

Please check the functional requirements of all services for requirements about errors. Each one of these should be mentioned in the belonging operation-section as well.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
