### ISSUE TITLE
ParameterService: AddDefinition - returning an error after sending a ParameterCreationRequest with a name set to NULL impossible

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#138]
The requirement  3.3.12.2.b says: "The name field must not be NULL [...](an invalid Error shall be returned in this case)."

When I try to test it there will always be thrown the exception: "org.ccsds.moims.mo.mal.MALException: Internal error encoding message" Thats because the Name-field of the ParameterCreationRequest-Object is not nullable. So during the encoding of the message on consumer side, the exception occures and the message will not be send to the provider. Because of that its not possible to return an INVALID-Error from the provider. 

Please check that, maybe the NULL-requirement has to be removed.

There is the same issue with other services that provide the addDefinition-Operation: ActionService, ParameterService, AggregationsService. AlertService, CheckService

**Comment by SamCooper** [comment]
So we are saying the XML specification of the structure used is already prohibiting the NULL? If that is the case then there is no need for the requirement.

**Comment by SamCooper** [comment]
Done.
