### ISSUE TITLE
All services: listDefinition - general description missleading

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#139]
The “General” section of the ListDefinition-operation is always saying: “The operation should be used in conjunction with the COM-Archive.”. But whats the use of the COM-Archive here? The operation always uses the ids in the internal provider list  as it also said in the sentence before: "The operation [...] requests the object instance identifiers of [...] supported parameters of the provider". The provider only knows which parameters it supports by its internal list. The COM-Archive doenst need to be requested anymore.

Please remove the sentence that the Operation should be used in conjunction with the COM-Archive.

There is the issue at all services that provide the listDefinition-Operation: ActionService, ParameterService, AlertService, CheckService and AggregationService

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
