### ISSUE TITLE
ParameterService: SetValue - use of newly created object unclear

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#140]
The requirement for the setValue-Operation 3.3.9.2.h says: "The service provider shall create new ParameterValueInstance objects for the updated parameter value."

It is not clear what should happen with the newly created object. Because of 3.3.6.2 "When a parametervalue update is published, the ParameterValueInstance object should be stored in the COM Archive" I suppose that the new ParameterValueObject will be saved in the COM Archive with the next publish message.
In the other operations which create an object it is defined what will happen with the object. E.g. the addDefintion Operation says: "The provider shall create a new ParameterIdentity and ParameterDefinition object and store it in the COM Archive."

I propose to extend the requirement and to add the fact what will happen with the created object, like: "The service provider shall create new ParameterValueInstance objects for the updated parameter value and store these in the COM-Archive when the next Parameter value update is published."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Updated to:

The service provider shall create new ParameterValueInstance objects for the updated parameter value and store these in the COM Archive.

Storing in the archive is independent of publishing.
