### ISSUE TITLE
ParameterService: GetValue receives unpublished values

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#141]
At the moment it is possible with the getValue-operation to get a value that hasnt been published yet. 
Imagin the case: 
    1. The value is updated via the setValue-Operation.
    2. This value is not published yet.
    3. Thus the ParameterValueInstance-Object is not saved in the archive and has no Id.
    4. Now the getValue Operation is called and the ParameterValueInstance-Object (that was just set with the setValue-operation) is returned. 
    5. The consumer gets a ParameterValue that is not saved in the archive and has no id.
    So its kind of an inofficial value which, I suppose, shouldnt exist.

Because of this case, I recommend to add another requirement that prevents this case. E.g. in the getValue Operation simply: "The ParameterValues must be published to store them in the COM Archive." or in the setValue-Operation: "The created ParameterValuesInstance-Object must be published until the next getValue-Operation is called to store it in the COM Archive."

**Comment by SamCooper** [comment]
I think the setValue operation would cause a publish and also a store so it will have an id.

Do you agree?

**Comment by NicolasVorwerg** [comment]
Yes, I think that's the way it should be.

**Comment by SamCooper** [comment]
Ok, I'll update the setValue operation to make this clear.

Accepted.

**Comment by SamCooper** [comment]
Done.
