### ISSUE TITLE
ParameterService - AddDefinition - Default enableGeneration-Value

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#142]
The High-Level-Requirement 3.3.2.e says: "By default report generation of newly added parameters shall be disabled, until specifically enabled."

So while the addDefinition-Operation, the field enableGeneration of the definition that will be newly created will always be set to false. This should be made clear in the addDefinition-Operation again, either as a note in the "General" part or as an own requirement. Otherwise, one could think, that "specifically enabled" could already be met by adding a definition where you set the enableGeneration field in the creationRequest-Object to true. In my oppinion this would be "specifically enabled" because you specifically set the parameterDefinitionDetails.

There is the same issue at one of the other services that provide the enableGeneration-Operation: AlertService.

**Comment by NicolasVorwerg** [comment]
A good possibility would be to add an INVALID error, if a definition is tried to be created with an EnableGeneration-field set to TRUE. This would also prevent surprises if you do set the EnableGeneration field to TRUE in the creation request and afterwards wait for the update to come, if you haven't noticed or misunderstood the requirement.

**Comment by SamCooper** [comment]
Thinking about it, why shouldn't we be able to add a definition that is initially enabled?

I think the general requirement should be changed.

**Comment by SamCooper** [comment]
WG review: The high level requirement should be updated/removed so that the operator can decide whether the parameter reporting is initially enabled/disabled.

Ensure similar behaviour on all other services.

**Comment by SamCooper** [comment]
Done
