### ISSUE TITLE
ParameterService: EnableGeneration - misleading description

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#143]
The general part of the parameter-Service 3.3.1 says: "[...] Groups must reference parameter definitions or groups of parameter definitions only." 

But groups are referencing parameter identities now.

Please change "parameter definitions" either to "parameter identities" or more general to "parameters". E.g. "[...] Groups must reference parameter identities or groups of parameter identities only."

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Done
