### ISSUE TITLE
GroupService: COM usage - wrong word

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#145]
The requirement: 3.9.4.a says: "The definitions of the conversions shall be represented as GroupDefinition COM objects."

The word "conversion" is wrong and must be "group".

Please Change the requirement to: "The definitions of the groups shall be represented as GroupDefinition COM objects."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
