### ISSUE TITLE
AggregationService: addDefinition - deprecated operation-signature

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#146]
The addDefinition-operations signature at the aggregation-service is currently: 
Input: AggregationDefinitionDetails-List
Output: Long-List 

this is deprecated and the new signature should be like the addDefinition-operation at the other services:
Input: AggregationCreationRequest-List
Output: ObjectInstancePair-List

Please update the operation.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done

**Comment by S-Gaertner** [comment]
Hi Sam, it seems you updated the operation partially. Please exchange `AggregationDefinitionDetails` with `AggregationCreationRequest` in `addDefinition` operation of aggregation service - otherwise one cannot supply an aggregation name.

**Comment by SamCooper** [comment]
Done properly this time!
