### ISSUE TITLE
All Services: requirement for wildcards missing

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#148]
The EnableGeneration-operation in the Aggregation-Service has a requirement saying: 
"3.7.10.2.d) the wildcard-value should be checked first, if found no other checks of supplied object instance identifiers shall be made". 
But other operations, that allow a wildcard, dont have this kind of requirement.

Please add this requirement to each operation at each service that allows a wildcard and returns errors.
E.g. for the AggregationService these are: 
    -getValue, listDefinition(also returns error because of #79 )

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
