### ISSUE TITLE
Aggregation-Service: ListDefinition - incomplete general description

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#149]
The general description of the listDefinition-operation is incomplete, because it is only mentioning the listing of the AggregationIdentity-objects but not the AggregationDefintion-objects. 

Please change it from:

"The listDefinition operation allows a consumer to request the object instance identifiers of the AggregationIdentity objects for the supported aggregations of the provider. The operation is expected to be used in conjunction with the COM archive which holds the actual AggregationIdentity objects." 

To:

"The listDefinition operation allows a consumer to request the object instance identifiers of the AggregationIdentity and AggregationDefinition objects for the supported aggregations of the provider. The operation is expected to be used in conjunction with the COM archive which holds the actual AggregationIdentity and AggregationDefinition objects."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
