### ISSUE TITLE
Aggregation-Service: List/Add Definition - wrong words

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#150]
1) 
The requirement 3.7.11.2.c in the listDefinition-operation of the Aggregation-Service says: "The response shall contain a list of matching AggregationIdentity and ParameterDefinition object instance identifiers."
The operation is not responding the ParameterDefinition but the AggregationDefinition. 

Please change it to:

"The response shall contain a list of matching AggregationIdentity and AggregationDefinition object instance identifiers."

2)
The general part of the addDefinition says: "The new AggregationIdentity and AggregationDefinition objects are expected to be stored in the COM archive by the provider of the parameter service."
The objects are not stored in the provider of the parameter-service but in the aggregation-service

Please change it to:
"The new AggregationIdentity and AggregationDefinition objects are expected to be stored in the COM archive by the provider of the aggregation service."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
