### ISSUE TITLE
AggregationService: unclear calculation of value to compare with the threshold

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#151]
In the Aggregation-Service the functional requirement 3.7.4.g is defined as: "If an aggregation is filtered, updates shall be generated only when the value of one or more parameters in the aggregation have changed by more than a given threshold since the previous generation.”

It is not clear which values have to be compared to check if the threshold was exceeded. The latest two sequently sampled values or the last updated-value with the newly sampled value?

Please make clear that the two values that will be compared are the last update value and the newly sampled value. The new requirement could be defined as the following:
"If an aggregation is filtered, updates shall be generated only when the value of one or more parameters in the aggregation have changed by more than a given threshold since the previous generated aggregation-update.”

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
