### ISSUE TITLE
Aggregation Service: invalid intervals unspecified

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#152]
In the Aggregation-Service the functional requirement 3.7.3.l says: "If the interval requested is not supported by the provider then an INVALID error shall be returned and the change rejected."

Please specify which one is "the interval" that shall be checked. I suppose it must be the filteredTimeout, updateInterval and each sampleInterval as all of them can trigger a sampling.
Please also add that it should be tested during the creation as well. 

So the new requirement could be defined as the following: 
"If the filteredTimeout-Interval, updateInterval or one or more of the sampleIntervals requested are not supported by the provider then an INVALID error shall be returned and the creation or change rejected."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
