### ISSUE TITLE
Aggregation Service: removeDefinition not removing AggregationDefinition

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#153]
In the Aggregation-Service the removeDefinition- requirement 3.7.14.2.d says: "Matched AggregationIdentity objects shall not be removed from the COM archive only the list of AggregationIdentity objects in the provider."

But besides the AggregationsIdentity objects, the AggregationDefinition objects will be removed as well. 

Please change it to the following requirement:
"Matched AggregationIdentity and AggregationDefinition objects shall not be removed from the COM archive only the list of AggregationIdentity and AggregationDefinition objects in the provider."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
