### ISSUE TITLE
AggregationParameterSet-Composite: missleading name and description of periodicFilter-field

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#154]
In the Aggregation-Service-DataTypes the AggreationParameterSet-Composite in the chapter 4.7.5 holds the field "periodicFilter" with a description that it: "[...] contains the filter to apply for filtered periodic updates when filters are applied.". That means the filter shall only be applied to periodic updates. 
But the "General" part of the Aggregation Service describes the case, that there can be applied a filter to ad-hoc aggregations as well: "Filtering can be applied to both periodic and ad-hoc aggregations." 

Please change the name of the field to a neutral name like "updateFilter" and delete the word "periodic" in the description.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
