### ISSUE TITLE
AggregationsService - missing requirements for enabling generation and filter

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#155]
The ParameterService has a functional requirement saying: "3.3.3.e The generationEnabled values can be set by using the enableGeneration operation."

The AggregationService does not have a requirement like this. Please add a similar requirement for its enableGeneration-operation and for the enableFilter-operation.

These requirements could be defined as:
"3.7.3.x The generationEnabled values can be set by using the enableGeneration operation."
"3.7.3.x The filterEnabled values can be set by using the enableFilter operation."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
