### ISSUE TITLE
Aggregation Service - missing requirements for filterEnabled-values

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#156]
In the Aggregation-Service the functional requirements contain two requirements defining the meaning of the values of the generationEnabled-field for generating updates. The filterEnabled-field behaves in the same way for filtering the updates, but doesnt have any requirements defining its values like the generationEnabled-field.

The requirements for the generationEnabled-field are defined as:
"3.7.3.a: The generation of updates for an aggregation shall be controlled by the generationEnabled Boolean value in the AggregationDefinitionDetails structure."
"3.7.3.b: Setting the generationEnabled field to TRUE shall enable generation of updates for a specific aggregation."

These dont exist for the filterEnabled-field. Please add new requirements for the filterEnabled-field:  
"3.7.3.c: The filtering of updates for an aggregation shall be controlled by the filterEnabled Boolean value in the AggregationDefinitionDetails structure."
"3.7.3.d: Setting the filterEnabled field to TRUE shall enable filtering of updates for a specific aggregation."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
