### ISSUE TITLE
AggregationsService: functionial fields that can be updated incomplete

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#157]
In the Aggregation-Service the functional requirement 3.7.3.k says: "The generationEnabled, filteredTimeout and updateInterval values of an AggregationDefiniton object can be set by using the updateDefinition operation." This requirement states out how you can enable/disable/change functions of the operation. 
Please add the fields: filterEnabled and sendUnchanged to the requirement and move it below the sendUnchanged requirement.

So the new requirement could sound like: 
"3.7.3.n: The generationEnabled, filterEnabled, filteredTimeout, sendUnchanged and updateInterval values of an AggregationDefiniton object can be set by using the updateDefinition operation."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
