### ISSUE TITLE
CheckService: addDefinition - deprecated Signature

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#158]
The addDefinition-signature is deprecated and holds two fields: one with the names and one with defintionsdetails. The other services usually have one field with a CreationRequestObject which should be used here as well. Please create such an object and change the signature from:
CheckInstanceTripleList addDefinition(StringList names, CheckDefinitionDetailsList newDefinitions)
to
CheckInstanceTripleList addDefinition(CheckCreationRequestList newDefinitions)

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Actually this is not possible due to the polymorphism restrictions of the MAL data type system.

**Comment by NicolasVorwerg** [comment]
Ok, then please remove the name field in the CheckDefinitionDetails as there are already the names given in the other operation argument.

**Comment by SamCooper** [comment]
Done.
