### ISSUE TITLE
CheckService: behaviour of removing referenced CheckDefinitions 

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#159]
At the moment, removing a CheckDefinition does not remove the CheckLink. This is defined in the requirement 3.5.16.2.f: "If the operation succeeds then the provider shall not allow new CheckLink objects to be created for the matched CheckIdentity anymore, existing CheckLink objects are not affected." 
What is the reason for explicitly not removing the CheckLink-Object as well? I propose that if you are removing a Check definition referenced in the CheckLink, the CheckLink should be removed as well. An other option would be to return a reference error like it is done in the updateDefinition-operation. Please clarify.

**Comment by SamCooper** [comment]
WG review:

The operation should return a REFERENCED error.
We should ensure that all operations in other services that have a similar effect have the same behaviour.

**Comment by SamCooper** [comment]
Done
