### ISSUE TITLE
CheckService: periodic checking and the enableCheck-operation

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#160]
In the enableCheck-operation the requirement 3.5.12.2.k is copy pasted from the ParamterService. Please specify what will happen when you enable the check. 
I propose to change it from:
"If the generation of updates is being enabled, and the parameter is defined as being periodic, then the provider shall generate an update immediately and start the update interval from that update."
to:
"If the check is being enabled, and the check is defined as being periodic in the check link, then the provider shall generate a check result immediately and start the checking interval from that check."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
