### ISSUE TITLE
CheckService: order of calculating difference between reference value and parameter value

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#161]
In the CheckService the function requirements 3.5.3 y and z are defined as "[...] the delta value shall be calculated as the difference between reference value and check value." But the example in 3.5.3.z shows it the other way around: "[...] For example, if the reference value is 8 and the parameter value is 14 then the calculation is (14 - 8) / 8 or 0.75 or 75%." Whats the right calculation order? Please harmonise. 
This is important as we decided in #124 that there is no absolute value used for the calculation.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
