### ISSUE TITLE
CheckService: Behaviour of periodic AND checkOnChange Checks

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#162]
In the CheckService the functional requirement 3.5.3.k is defined as: "For periodic check evaluations to occur the checkOnChange value must be FALSE, it is not possible to request periodic and change based checking concurrently."

Please specify the behaviour if the checkLink is defined to be periodic and the checkOnChange value is TRUE.  I propose to return an INVALID Error in this case. So the new requirement could be defined as:
"If the checkInterval is not '0' and the checkOnChange Value is TRUE, then an INVALID error shall be returned."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Added to the addParameterCheck operation.
