### ISSUE TITLE
CheckService: invalid intervals unspecified

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#163]
The functional requirement 3.5.3.n is defined as: "If an interval that is not supported by the provider is requested, then an INVALID error shall be returned, and the change shall be rejected." Please specify which intervals should be checked. I propose the checkInterval or maxReportingInterval but what about the nominalTime or violationTime? I don't think that these have to be checked but it should be made clear. 
Please also add that it should be tested during the creation as well. 

So the new requirement could be defined as the following:
"If a checkInterval or maxReportingInterval that is not supported by the provider is requested, then an INVALID error shall be returned, and the creation or change shall be rejected."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Changed to:

If a checkInterval or maxReportingInterval that is not supported by the provider is requested (both on creation and update of the check), then an INVALID error shall be returned, and the change shall be rejected.
