### ISSUE TITLE
CheckService: when is GetSummaryReport Operation returning UNKNOWN error

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#164]
In the CheckService the GetSummaryReport operation has two interpretations of how an UNKNOWN Error could be returned:

Firstly, the checkIdentityIds will be checked for an UNNOWN Error first and if found the operation returns this error and terminates. 
Or secondly the id will be checked during sending the update-messages. Sothat known checkIdentityIds will return their checkResult in their update message and unknown checkIdentityIds will return an error in their update message. In this case the operation doesnt terminate because of the error.

Please specify, which way is the right one.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Changed to:
If a requested check is unknown then an UNKNOWN error shall be returned in the ACKNOWLEDGE message and the operation shall end.
