### ISSUE TITLE
CheckService: GetCurrentTransitionList-operation unclear behaviour of the CheckResultFilter

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#165]
In the GerCurrentTransitionList-Operation in the CheckService there are two interpretations of how to use the filter. 
First interpretation: you are filtering the CheckResults for all of the given CheckIds first and then you are filtering on the resulting list for all of the given Parameter Ids (so you use the two lists indepentently)
Second interpretation: you are filtering the CheckResults for the Pair (first CheckId|first ParameterId) then you are filtering for the next Pair(second CheckId|second ParameterId)and so on (so you combine the two lists to one list of pairs).

Both behaviours are just fine, but it should be made clear as both lead to different results. In my opinion the second one is the more intuitive one (and also the interpretation I thought of first).

Please specify.

**Comment by SamCooper** [comment]
WG review:

The three filters should be applied to the checks using "AND" logic.

The operation should also support groups, so "request all the POWER parameters in violation".

**Comment by SamCooper** [comment]
Done
