### ISSUE TITLE
CheckService: GetCurrentTransitionList-operation not only returning violations

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#166]
In the CheckService the GetCurrentTransitionList operation holds the requirement 3.5.8.2.g defining: "The PROGRESS pattern is used to allow the possibly large list of current violations to be split into several updates." 
But you could also use the operation to filter for successful operations or other states. 

Please change the requirement to a more general version like: 
"The PROGRESS pattern is used to allow the possibly large list of current filtered check results to be split into several updates."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
