### ISSUE TITLE
CheckService: contradicting requirements for a Constant-Check

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#167]
There are two requirements for the ConstantCheck that are contradicting. One requirement is saying that the given value has to evaluate to one of the constant values and the second one that it has to pass evaluation against all of the constant values.

3.5.2.e.a: "When performing a constant check, the check service shall: check that the parameter value evaluates to one of the expected values."
and 3.5.3.aa: "For a constant check the result shall be declared successful only if the parameter value passes evaluation against the complete set of constant values in the definition."

Please hamonize the two requirements.

I recommend to change the second requirement to:
"For a constant check the result shall be declared successful only if the parameter value passes evaluation against one of the constant values in the definition."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
