### ISSUE TITLE
CheckService: (re)moving of CheckTransition COM Event Object requirement

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#168]
In the CheckService the requirement 3.5.4.k is defined as : "Violations of a check evaluation or the maximum reporting interval expiring shall be represented as CheckTransition COM events." This requirement is uncomplete and should be moved into the "COM Event Service usage". The only one requirement in this section in turn is uncomplete as well as it is not mentioning the event after a maximum reporting interval.

Please remove the 3.5.4.k requirement and add the following requirement to the "COM Event Service usage" section:
"3.5.5.2 When the maximum reporting interval is expired the generated check result shall be represented as a CheckTransition COM event."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I added the extra event requirement but changed 3.5.4.k to:
Changes in the state or result of a check shall be represented as CheckTransition COM events.

As it is there to describe what that object is for.
