### ISSUE TITLE
CheckService: doubled requirement for publishing a CheckTransition-Event:

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#169]
There are two requirements in the Functional Requirements, defining when to publish a CheckTransition-Event:
First: 3.5.3.q: "If there is a change in the result of the check evalutation then a CheckTransiition event shall be published."
Second: 3.5.3.ii: "Each transition in the state of a check shall cause the generation of a CheckResult and a CheckTransition event."

I dont see the cases the first requirement is covering but the second one is not. Because if the result changes, the state changes and then 3.5.3.ii is used anyway. 
Please check that and I recommend to either add an example where the use of 3.5.3.q is made clear or only keep the 3.5.3.ii.

**Comment by SamCooper** [comment]
Accepted

**Comment by NicolasVorwerg** [comment]
Ok there are cases: e.g. if you have a LimitCheck and the parameters value is at first below the lower limit and afterwards above the upper limit. 
Now I think its best to merge the both requirements to:
"ii)Each transition in the state or the result of a check shall cause the generation of a CheckResult and a CheckTransition event."

**Comment by SamCooper** [comment]
Done.
