### ISSUE TITLE
CheckService: TriggerCheck, ParameterService GetValue, AggregationService GetValue: unclear influence on other operations

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#170]
Please define in the operations TriggerCheck (CheckService), GetValue(ParameterService) and GetValue(AggregationService) (so in operations that seem not to influence other operations) excplicitly what should happen internally and what should not happen. Especially this is important for each of their periodic checks/updates and how these are influenced.

More specifically:
Please define how the TriggerCheck affects periodic checks: E.g. is it increasing/reseting the nominalCounter? Is the Periodic Interval being reseted? Is the maxReportingInterval being reseted?
Same with the GetValue in the ParameterService: Is it reseting the update Interval? Is it publishing a value?
Same with the GetValue in the AggregationService: Is it reseting the reporting Interval? Is it publishing a value? Will this value be filtered? Will the next periodic aggregation be filtered against this value?

A requirement to define that could sound like: 
For the TriggerCheck operation:
"Triggering a check shall ignore the nominalTime, nominalCount, violationTime and violationCount-fields and requests an immediate evaluation of the checks."
"Triggering a check during a periodic check shall not influence the periodic check (e.g.: it is not resetting the updateInterval-timer, the successive valid samples that passed/violated the check or the maxReportingInterval-timer)"
or if it affects it:
"Triggering a check during a periodic check shall influence the periodic check in the way that it is resetting the updateInterval-timer, the successive valid samples that passed/violated the check and the maxReportingInterval-timer."

For the getValue operations in the Parameter-Service a requirement to define that could sound like: 
"The getValue operation is not publishing the returned values."
"Using the getValue operation on a periodic parameter shall not reset the updateInterval-timer."
or if it affects it:
"Using the getValue operation on a periodic parameter shall reset the updateInterval-timer."

For the getValue operations in the Aggregation-Service a requirement to define that could sound like: 
"The getValue operation is not publishing the returned aggregation-values."
"During the getValue operation the filter shall not be applied."
"Using the getValue operation on a periodic aggregation is not influencing the next periodic aggregation value in any way (e.g.: it is not reseting the updateInterval-timer or filtered-Timeout-timer and the next periodic aggregations will not be filtered against this value)"
or if it affects it:
"During the getValue operation the filter shall be applied."
"Using the getValue operation on a periodic aggregation is influencing the next periodic aggregation value in the way that it resets the updateInterval-timer and filtered-Timeout-timer and the next periodic aggregations will be filtered against this value"

Probably there is an equivalent operation in the Statistic-Service which I havent implemented yet. Please have a look there too.

Please add these or similar requirements to be explicitly clear about how the operations behave and influence others.

**Comment by SamCooper** [comment]
Accepted

**Comment by NicolasVorwerg** [comment]
Are the answers to the questions that I asked above obvious for you? I am asking because you haven't marked it to be discussed. What would be the behaviour in general here then?

**Comment by SamCooper** [comment]
I read these as "please make it clear the effect these operations have on the background period tasks such as limit checking, statistic reporting etc".

Is that correct?

**Comment by NicolasVorwerg** [comment]
Yes, the effect on background periodic tasks and which/if objects will be created or updated. Im just thinking that we don't miss the chance to discuss the issue, if needed. But if its all clear then its fine.

**Comment by SamCooper** [comment]
Done
