### ISSUE TITLE
CheckService: unharmonized description of evaluating limit and delta check

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#171]
In the CheckService the high level requirement 3.5.2.e.a for the limit check is defined as: "[When performing a limit check, the check service shall] check that the value of a parameter lies within a pair of limit values if set to violate in range, or outside a pair of limits if set to violate outside the range."
So here the check is described to check for the violating case. 

In contradiction to that is the description of the reference check . Requirement: 3.5.2.f.a: [When performing a reference check the checkService shall] check that the parameter value evaluates to the referenced value.  
So here the check is described to check for the successful case. 

The limit check and delta check are described for the violating case.
The reference check, constant check and compound check are described for the successful case.

I recommend to harmonize the requirements and change the requirement for the limit check and delta check to describe a successful case as well.
So the new high level requirement 3.5.2.e.a: of the limit check could sound as the following: 
"[When performing a limit check, the check service shall] check that the value of a parameter lies within a pair of limit values if set to violate outside the range, or outside a pair of limits if set to violate in range."

This seems more convenient to me and prevents possible confusion.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
