### ISSUE TITLE
CheckService: listDefinition - missing requirement for returning object type

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#172]
In the listDefinition-operation of the CheckService, please update the requirement: 3.5.14.2.c so that the type of the actual check definition is defined to be returned as well. 
So from:
"The response shall contain a list of matching CheckIdentity, CheckDefinition, and actual check definition object instance identifiers."
To:
"The response shall contain a list of matching CheckIdentity, CheckDefinition, and actual check definition object instance identifiers and the actual check definition object type."

**Comment by SamCooper** [comment]
I will have to check this.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
