### ISSUE TITLE
CheckService: wildcard value for getSummaryReport/getCurrentTransitionList different than usual

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#174]
In the GetSummaryReport- and GetCurrentTransitionList-operation of the CheckService the wildcard value to retrieve all checks is an empty list. But usually, e.g. in the RemoveDefinition- or EnableCheck-Operation, if there is a list of object instance identifiers, the wildcard is the value of "0". 

Please harmonize this sothat you are either always using the '0' value or the empty list as the wildcard value.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
