### ISSUE TITLE
CheckService: sample based field in DeltaCheckDefinition redundent

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#175]
The sampleBased-field in the Composite:DeltaCheckDefinition is described to contain the information: "If TRUE, then the delta values are calculated based on when the value updates; otherwise, the delta value is calculated based on an internally calculated time interval." In other words, if the value of the parameter changes or if an interval is up, the check shall be evaluated. But this function is already met with the checkOnChange and checkInterval fields in the CheckLinkDetails. 

Please remove the sampleBased field, or explain the difference to the CheckLinkDetails checkOnChange- and checkInterval-fields.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Field has been removed.
