### ISSUE TITLE
CheckService: unclear use of previous- and currentEvaluationResult-fields

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#177]
The Composite: CheckResult contains the fields previousEvaluationResult (of type: MAL::Boolean) and currentEvaluationResult (of type MAL::Boolean) containing information about the result of a check evaluation. But these fields are misleading. This is because these actually dont contain the information about IF the evaluation was successful or violated but rather HOW it violated. This is only important for limit or delta checks: if it violates the upper limit the currentEvaluationResult is true, if it violates the lower limit the result is false (as defined in 3.5.3.cc, dd). 

I recommend to rename the fields to previous- and currentViolationResult and describe for each check (also for the compound, constant and reference checks where its not defined yet at all) how these fields will be filled.
Furthermore please consider to change the type of the fields. I think a Boolean-Value is semantically not correct and an enumeration with defined states would be more convenient to understand the actual meaning.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I have removed those fields, and the corresponding requirements as they only added detail in one small case (limit check when violate in range was false) and that can be determined by just knowing the check limits.
