### ISSUE TITLE
CheckService: homogenizing word(-groups) for functional descriptions 	

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#178]
In the requirements there are some words or word-pairs describing a specific function during a service. E.g. "check evaluation" means that the value of a parameter is being checked. But sometimes there are different words for the same function or words are not unambigious. In the following list I put all of these words making the understanding of the whole system harder and stated the more precise words behind.
- 3.5.3.u: "[...]have consistently passed the check shall a new check result be calculated" -> firstly change "passed the check" to "passed the check evaluation"; secondly "shall a new check result be calculated": better change it to "shall a new check state and check result be calculated". This states out what you actually do and furthermore connects it with the requirement 3.5.3.ii which says "each transition in the state of a check shall cause the generation of a CheckResult [...]", sothat its easier to understand the whole process.
- 3.5.3.v -> same as 3.5.3.u
- 3.5.3.p "The check execution may also be triggered by the triggerCheck operation." The words "check execution" are never used at another position, you can just guess what it means. Better would be "The triggerCheck operation may trigger a check evaluation and immediatly publish the result in a CheckTranisitionEvent if the check violates."
- 3.5.3.r: "If the check result cannot be determined [...] the associated CheckResult shall contain UNCHECKED for the checked states [...]" -> Change "If the check result" to "if the latest CheckResult" because the way it is described at the moment, you could think that you have to try to calculate a check result but what you actually do is looking for the latest CheckResult object that was generated.
- Figure 3-7 "Flow Chart for determining the status of a Check": There is one condition saying "Is entity being checked VALID or using raw and INVALID_CONVERSION". Please exchange the word "entity" with the word "parameter" as you always check a parameter here.
- Figure 3-6 "Check Service Nominal Sequence": In the sequences "Periodic Check" and "Parameter Update detected", it is stated that if the "Check violated" a CheckTransition Event will be published. In these two cases if would be more precise to define, that if a "Check transition" occurs the CheckTransition Event will be published.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
