### ISSUE TITLE
CheckService: COM-links of the CheckLink-Object

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#180]
This is a special case of the changes that will be applied by the issue " #179 All Services: unification of ids referencing other service-objects" and maybe needs discussion.

Of special interest is the CheckLink-Object in the CheckService. At the moment it has a related-link to the CheckDefinition-Object and the source-link to the ParameterDefinition-Object.
After applying changes of the RID #179 , the source-link should reference to the ParameterIdentity-Object, which is good, because at the moment updating the ParameterDefinition would cause an update of the CheckLink as well. 

The question is: what about the related link? Should it keep on referencing to the CheckDefinition or reference the CheckIdentity now? Actually I think, the CheckIdentity-Objects has exactly the function that the CheckDefinition-Object was former be created for: being a "parent"-object you can reference from the CheckLink-Object. So as we have a new parent object now, the CheckDefinition is not necessary anymore.

Please check if there is another reason for the CheckDefinition-Object that makes it inevitable.

**Comment by SamCooper** [comment]
I agree, the CheckDefinition object seems redundant. I will check to ensure this is still the case but I think it is.

So:
CheckLink->rel->CheckIdentity
CheckLink->src->ParameterIdentity

but also how does the links between CheckIdentity and xxxCheck (definition) get changed? Do we leave it with the xxCheck object pointing at the CheckIdentity?

**Comment by NicolasVorwerg** [comment]
Yes I would leave it the way it is: Actual Check Definition->rel->CheckIdentity . That's the way its done in all services.

**Comment by SamCooper** [comment]
But it does mean that you cannot easily find the definition of a check from its identity, but I suppose that is the same for all services.

**Comment by NicolasVorwerg** [comment]
Exactly, the developer has to find a solution for this anyway.

**Comment by SamCooper** [comment]
Ok, accepted then. No need to discuss at meeting.

**Comment by SamCooper** [comment]
Done.
