### ISSUE TITLE
CheckService: updating nominal/violation fields should return INVALID error

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#181]
The requrirement 3.5.3.s is defined as: "In a CheckDefinitionDetails only one of nominalTime and nominalCount is permitted to be zero, an INVALID error shall be returned from the addDefinition operation if this is not the case." This requirement is only talking about the addDefinition but not about the updateDefinition operation. 
Please add that the INVALID error should also be returned when updating the nominal time and nominal count field with the updateDefintion operation.
The new requirement would be: 
"In a CheckDefinitionDetails only one of nominalTime and nominalCount is permitted to be zero, an INVALID error shall be returned from the addDefinition or updateDefinition operation if this is not the case."

There is the same issue with the violation fields (requirement 3.5.3.t).

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
