### ISSUE TITLE
CheckService: missing requirement for returning a REFERENCED error in the updateDefinition-operation

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#182]
Usually if an operation returns an error there are two requirements: One in the operation "Structures"-part and one in the "ERROR"-part.
For the "REFERENCED "-error there is only the requirement in the "ERROR"-part but no requirement in the "Structures"-part. 
Please add such a requirement.

The new requirement could sound like:
"j) If the check to be updated is currently being used by a CheckLink-Object, a REFERENCED error shall be raised."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
