### ISSUE TITLE
CheckService: addParameterCheck is not storing new CheckLink object in the archive

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#183]
Usually service-operations that create objects that have to be stored in the archive have a requirement saying: e.g in the AddDefinition of the CheckService: "h) The provider shall create a new CheckIdentity, CheckDefinition, and actual check definition objects and store them in the COM archive."
This requirement is missing for the addParameterCheck-operation.

Please add this requirement that could like:
"The provider shall/should create a new CheckLink-object and store it in the COM archive."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
