### ISSUE TITLE
CheckService: getCurrentTransitionList-operation unclear how to split response into several checkSummaries 

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#184]
In the GetCurrentTransitionList-Operation there is a requirement saying: "g) The PROGRESS pattern is used to allow the possibly large list of current violations to be split into several updates." But its not clear how to split this large list into the several updates. In contrast to that the similar operation GetSummaryReport has a requirement saying: "d) The returned updates and final response shall contain an entry for each requested CheckIdentity." 

Please add a requirement to the GetCurrentTransitionList-Operation defining when exactly the "list of current violations" will be split into several updates or that its implementation specific. E.g.:
"The returned updates and final response shall contain an entry for each filtered CheckIdentity."
or
"The size of the lists returned in each update and final response is implementation specific."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
