### ISSUE TITLE
CheckService: checkedValue-field for a the compound-check-result unclear

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#185]
The composite "CheckResult"s field "checkedValue" is described that "This is the value of the entity at the time of a check state transition, or if it is an update due to the CheckDefinition maxReportingInterval expiring, then it is the value of the entity when the interval expired." 
Its not clear which value this field contains for a result of a compound check. Only null or the number of checks in violation would makes sense here. I think it should be the number of checks in violation.

Please update the description to e.g.: 
"This is the value of the parameter or for a compound check the number of checks in violation at the time of a check state transition, or if it is an update due to the CheckDefinition maxReportingInterval expiring, then it is the value or the number when the interval expired."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
