### ISSUE TITLE
CheckService: composite changes for considering compound checks

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#186]
At the moment there are two composites in the CheckService that dont consider the compound check. These dont consider the compound check in the way, that it is not linked to a parameter what makes some fields unnecessary. For this case I recommend to change these fields to be nullable:
Composites:
- CheckLinkDetails -> useConverted, checkOnChange, checkInterval (because by definition compound checks will always be evaluated if one of its check changes)
- CheckSummary -> parameterId

Please change the fields to nullable and add in the description that these can only be null for a compound check.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done, I have stated that the Booleans should just be ignored as making them Nullable doubles the size of them in the encoded packets.
