### ISSUE TITLE
ActionService: generation of Acceptance activity event unclear

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#187]
In the ActionService the COM Activity Service Usage requirement: 3.2.8.e is defined as: "e) An Acceptance activity event for the ActionInstance object shall be generated when an action is received by the destination provider and after any pre-execution checks being performed as part of the submitAction operation." This requirement can be misunderstood, if you interpret the "and" as a logical AND. Then there would only be one event generated. 
Furthermore there is no requirement specifying how to fill the success-fields in the body of the Acceptance activity events. 

Please change the requirement in a way that you know that there are two events generated and add requirements specifying their body. 

I propose to split the requirement into two and add some, what would result in the following requirements:
"e) The first Acceptance activity event for the ActionInstance object shall be generated when an action is received by the destination provider as part of the submitAction operation."
"f) The body of the first ActivityAcceptance event object shall be populated with TRUE."
"g) An Acceptance activity event for the ActionInstance object shall be generated after any pre-execution checks being performed as part of the submitAction operation."
"h) The body of the second ActivityAcceptance event object shall be populated with the pre-execution checks result"  
(this is partly a child RID for #103 )

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I have changed the original requirement to:
- The Acceptance activity event for the ActionInstance object, separate from the Acceptance activity event generated for the suibmitAction operation, shall be generated when an action is received by the destination provider and after any pre-execution checks have been performed.
- The body of the ActivityAcceptance event object shall be populated with the pre-execution checks result.

Reopen and comment if you disagree.
