### ISSUE TITLE
ActionService: wording of requirement missunderstandable

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#188]
In the ActionService the COM Activity Service Usage requirement: 3.2.8.c is defined as: "c) The COM activity events shall be generated as defined in the COM activity tracking service for the submitAction operation." This wording could let you think that there is a explicitly defined COM activity tracking service for the submitAction operation. But thats not the way its meant to be. Actually the submitAction-events shall be generated as defined in the COM activity tracking service.

Please just change the wording to: 
"c) The COM activity events for the submitAction operation shall be generated as defined in the COM activity tracking service."

**Comment by SamCooper** [comment]
Done
