### ISSUE TITLE
ActionService: unclear behaviour of sending the progress steps Execution Events

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#190]
The requirement 3.2.5.b in the COM Event Service Usage part is defined as: "b)  The Execution event may be reported many times as it is used to report each stage in the execution of the action." But its never defined when each of these progress-steps is reached. Thus its not defined when exactly each of these Execution-Events must be send. 

Please specify when a progress stage is reached or if it wont be defined that it is implementation specific.
So e.g.: 
"Each progress step shall be reported after 1/progressStepCount's submitted attributeValues were processed."
or 
"Its implementation specific when a progress step is reached and the Execution-event will be reported."

**Comment by SamCooper** [comment]
It is implementation (or actually Action specific) when they are reported. I've added in the text though.
