### ISSUE TITLE
Action service update definition – handling of different size lists

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#191]
Action::updateDefintion does not specify what should happen if the two IN lists are of a different size.  It is recommended the same approach should be taken as is specified in  Alert::updateDefintion –
The number of entries in the two lists shall be the same size otherwise an INVALID error shall be returned.

However the description should state that the extra information field in the error  is not used.

**Comment by SamCooper** [comment]
Done.
