### ISSUE TITLE
Action UpdateDefinition – existing definition

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#192]
Clause g) states:

> The provider shall create a new ActionDefinition object and store it in the COM archive.
> It should also state that the existing object is deleted and removed from the archive.

A related issue – the introductory text states –

> The operation must not be used to change the name of an existing action
> This is now out of date as the operation cannot be used to change the name.

**Comment by SamCooper** [comment]
It currently states:
- The provider shall create a new ActionDefinition object and store it in the COM archive.
- The new ActionDefinition object shall be the current ActionDefinition used for the specific ActionIdentity.

The "removeDefinition" operation has the following text in its general desciption:

> The operation does not remove the ActionIdentity or ActionDefinition object from the COM archive, merely removes the objects from the provider. This permits existing, and completed, ActionInstance objects to continue to reference the correct ActionIdentity and ActionDefinition objects in the COM archive.

Do you think adding a variation on that would be correct?

Second point, yes that has been fixed.

**Comment by ivandank12** [comment]
Yes that would be clearer

**Comment by SamCooper** [comment]
Done
