### ISSUE TITLE
Parameter/AggregationService: updateDefinition requirement missing

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#193]
Usually in the updateDefinition-operation there is a requirement saying: "The number of entries in the two lists shall be the same size otherwise an INVALID error shall be returned." This requirement does not exist in the Parameter- and AggregationService

Please add this requirement to the updateDefinition-operations in the two services.

Furthermore, please add this error to the "ERROR:INVALID" section sothat it sounds like: 
"The two input lists do not contain the same number of entries."

**Comment by SamCooper** [comment]
Done
