### ISSUE TITLE
Statistic Service: renaming of enableGeneration to enableReporting

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#195]
The enableGeneration-operation sets the value of the field reportingEnabled. Thats a bit confusing.

Please either rename the operation to enableReporting (as its done in the CheckService -> enableCheck as well) or rename the StatisticLinkDetails field "reportingEnabled" to "generationEnabled".

**Comment by SamCooper** [comment]
Done
