### ISSUE TITLE
Statistic Service: two ways of returning an UNKNOWN error for EnableGeneration-operation   	

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#197]
In the StatisticServcice the requirement 3.6.12.2.g in the enableGeneration-operation is defined as: "g) If a requested StatisticFunction or Group object is unknown then an UNKNOWN error shall be returned." In constrast to that the "Error"-part requirement 3.6.12.3.1.a says: "a) One or more of the requested StatisticLink is unknown.". 

Please change the requirement in the "Error"-part to:" a) One or more of the requested StatisticFunction or Group objects is unknown.".

**Comment by SamCooper** [comment]
Done
