### ISSUE TITLE
StatisticService: unclear behaviour of enableGeneration on reports after collection interval

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#198]
In the Statistic Service the requirement 3.6.12.2.e of the enableGeneration-operation is defined as: "If the enableInstances field contains a value of TRUE then reports of matching StatisticLink objects shall be generated, a value of FALSE requests that reports will not be generated." 

Please define if the generation of a report after the collection interval will be enabled/disabled as well or only the report after the reporting interval. 

E.g if both of it will be enabled/disabled the new requirement could sound like: 
"If the enableInstances field contains a value of TRUE then reports after the reporting interval and after the collection interval of matching StatisticLink objects shall be generated, a value of FALSE requests that these reports will not be generated." 

Or if its only the reports after the reporting time that will be enabled/disabled explicitly define that reports after the collection interval will not be enabled/disabled. Then this requirement could sound like: 
"If the enableInstances field contains a value of TRUE then reports after the reporting interval shall be generated, a value of FALSE requests that these reports will not be generated. The generation of reports after the collection interval is not affected."

**Comment by SamCooper** [comment]
It is the former.

Done.
