### ISSUE TITLE
Statistic Service: requirement missing when to evaluate the statistic value

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#199]
There is no requirement saying when the statistic value will be evaluated. Only in the Figure 3-9 "Statistic Service Nominal Sqeuence" there you can see, that the parameter statistic will be evaluated after every sampling and after every collection interval. 

Please create a requirement saying like: "The statistic value for a parameter shall be evaluated after each sampling of the parameter and after the collection interval is elapsed." Whereas I dont see a case where its necessary to evaluate the statistic value after the collection interval, as when there was a sampling it was already evaluated after the sampling and if there wasnt, there is nothing to evaluate.

Please check that and add the requirement.

**Comment by SamCooper** [comment]
Done.
