### ISSUE TITLE
Calculation of a new check result

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#20]
The algorithm specifies in section 3.5.3 to compute a new check result is the following one:

u)  Only when the nominalCount number of successive valid samples including the current one over a nominalTime time period of the checked parameter have consistently passed the check shall a new check result be calculated.
v)  Only when the violationCount number of successive valid samples including the current one over a violationTime time period of the checked parameter have consistently failed the check shall a new check result be calculated.

At CNES we use the violationCount (resp. nominalCount) and/or the violationTime (resp. nominalTime) differently from what is proposed. 
For instance, the violationCount is used when we want to avoid triggering an alarm on "outlier" values, therefore n successive valid samples must have consistently failed the check to trigger the computation of a new check result. In this case, as the samples are consecutive, what is the interest of specifying in addition a time constraint ? What happens if the number of successive failed samples is reached before the violationTime has elapsed ?

On the opposite, we use the violationTime  in combination with the violationCount when we try to detect the occurrences of a phenomenon over a period of time and to take an action it the phenomenon happens more than n times in a period of time. In that case we trigger a new check computation if n valid samples  over a period of time have failed the check, but the samples do not have to be successive. 

Therefore in our legacy M&C systems, either the violationTime is NULL and in that case the n failed samples must be consecutive to trigger a new check result, or the violationTime is not NULL and the samples that have failed the check do not have to be consecutive.

For the nominalCount (resp. nominalTime), the logic is the same.

Can you clarify statements u) and v) and explain how they can fit the 2 CNES use cases ?

**Comment by SamCooper** [comment]
To be discussed with Ian @ London

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Updated to support the CNES cases, nominalTime etc are set to '0' to remove the time constraint and add in the consecutive constraint.
