### ISSUE TITLE
Statistic Service: requirement for sending a report after each collection interval missing

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#200]
In the High Level Requirements there is specified that the value is sampled every sample interval, the report sent after each reporting interval but not what happens after the collection interval. 

Please either add a new requirement or add this fact to the existing requirement 3.6.2.h like: "h)The current statistics value shall be reported every reporting and collection interval if generation is enabled."

**Comment by SamCooper** [comment]
Related to #68

**Comment by SamCooper** [comment]
Done
