### ISSUE TITLE
Statistic Service: missing invalid error in getStatistics operation

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#201]
Usually if there are Arguments that are possibly Group-Ids there is a requirement defined like: "b) If the isGroupIds field is TRUE, the requested Group, or the Group objects referenced by that Group, must contain ParameterIdentity objects otherwise an INVALID error shall be returned."
This requirement is missing in the getStatistics-operation of the StatisticsService.

Please add this requirement in the "Structures"- and in the "Error"-part of the getStatistics-operation.

**Comment by SamCooper** [comment]
Done
