### ISSUE TITLE
Statistic Service: is ResetEvaluation creating StatisticValueInstanceObject

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#202]
In the ResetEvaluation-operation the general description says that the operation is "[...] optionally returnung the evaluation up to that point". This could be understood like there is the latest report returned or that a new report is created and returned. There is only one hint about this question in requirement 3.6.4.o: "o) If the StatisticValueInstance object was a result of either a resetEvaluation or getStatistics operation call then the source link shall be the COM OperationActivity object of the operation."

So seeing this requirement the answer would be yes, there is a new object created. But having a look to the RID #199 tere is again the question: is it really necessary to evaluate the statistic value again? As the value is always evaluated after each sampling and creating a new object brings the same result as the latest object. 

So if all the above is correct, please remove the part in the requirement 3.6.4.o that the resetEvaluation-operation creates an object. 
The requirement that will be added in RID #199 makes it clear that no new object is created but the latest created one be returned.

**Comment by SamCooper** [comment]
Done
