### ISSUE TITLE
All Service: specifiing the word "current" 

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#203]
In some services there is the situation, that there are object created periodically and at the same time could be created by a trigger. In these services its ambigious what is meant to be "current". Is it the latest created value or should a new value be created? For example in the Statistic Service´ operation getStatistics the general description says: "The getStatistics operation returns the current value for a requested set of statistic evaluations." Which is meant to create a new value and return it. On the other hand in the High-Level requirement 3.6.2.h of the Statistic Service: "h)    The current statistics value shall be reported every reporting interval if generation is enabled." Here it means that the latest created value will be returned and no new value will be created. 

Please update the following positions and specify what is meant by "current". Here are the positions where its ambigious:
- Statistic Service: 3.6.2.h: "The current statistics value shall be reported every reporting interval if generation is enabled." -> Thats a newly created value
- Statistic Service:´Operation "getStatistics" -> the general description says: "The getStatistics operation returns the current value for a requested set of statistic evaluations." -> Thats the latest created value
- Statistic Service: 3.6.3.a: "A consumer may request the current status of the statistical evaluations using the getStatistics operation." -> Thats the latest created status
- Statistic Service: 3.6.8.g: "If the returnCurrentEval Boolean field is TRUE then the current evaluation result for each of the matched links shall be returned before resetting, otherwise a NULL is returned." -> That is a newly created value 
- CheckService: getCurrentTransitionList -> general part: "The getCurrentTransitionList operation allows a consumer to obtain the current result of a number of checks filtering on check state." as well as its requirmenets: "r)  The returned list shall contain an entry for each matched check returning the object instance identifier and current CheckResult for that CheckLink object." and "s)    The PROGRESS pattern is used to allow the possibly large list of current filtered check results to be split into several updates."
  -> I suppose latest created values.

Thats all that I could find. Please update these positions.

**Comment by SamCooper** [comment]
Done
