### ISSUE TITLE
Submit action handling of argument fields

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#207]
The submitAction operation has a parameter actionDetails, which contains three lists associated with the action arguments: **argumentValues**, **argumentIds** and **isRawValue**. The description relating to **argumentIds** states it must be the same size as the same field in the Action definition. 
However, the description for **argumentValues** and **isRawValue** does not specify a constraint for the size. The description should say that the size should be equal to the number of arguments defined in the definition. If it is not an INVALID error shall be returned, (with the extra information field not used)

**Comment by SamCooper** [comment]
Done.
