### ISSUE TITLE
Get Statistics unclear

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#208]
The description for **Get Statistics** is unclear.  The text states it returns the current value for a requested set of statistic evaluations. 
Does that mean the parameters and functions must be used to identify a set of existing Statistic Definitions and the last value calculated for each returned?
Or does this operation not relate to existing statistics definitions – and should the parameters and functions be used to identify a set of statistics evaluations to be performed. If so over what period should the calculation be performed? A period (and collection interval) is required for the result to be deterministic.

**Comment by SamCooper** [comment]
It should specify a filter on the existing link objects, So filter on MEAN for parameters [a, b, c] for example.
