### ISSUE TITLE
Add Parameter Return type

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#209]
This function returns a list containing the for the new StatisticLink and StatisticLinkDefinition objects. But the elements of the list are of type ObjectInstancePair and it is not specified how the StatisticLink and StatisticLinkDefinition identifiers map to the ObjectInstancePair fields. 

It is recommended either the mapping is specified or a specific structure is introduced.

**Comment by SamCooper** [comment]
Done
