### ISSUE TITLE
behaviour of a percentage based delta threshold when the reference value = 0

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#21]
requirement z) of section 3.5.3 states:

z)  For percentage based delta thresholds, the percentage is calculated as the arithmetic difference between the reference value and the parameter value, as a percentage of the first valid sample where the value 1.0 is 100 per cent. For example, if the reference value is 8 and the parameter value is 14 then the calculation is (14 - 8) / 8 or 0.75 or 75%

As the reference value is a TM parameter whose value changes over time, what should the service behaviour be if the reference value takes the value 0 at one point ? I suppose that an error code should be raised but the service should not "crash". 

Would it not be good to define this error code in the standard ?

**Comment by SamCooper** [comment]
The calculation is actually incorrect! It shouldn't be as a percentage of the first valid sample but as a percentage of the maximum possible value for the integer type.

For example if the type is a signed 16bit integer then it is a percentage of 32767. I'll have to work out how best to phrase this but that is the correct calculation. 

Doing it as a calculation based on the first valid value makes it completely unpredictable!

**Comment by SamCooper** [comment]
Ok, after discussion, the original calculation stands. We need to add text to warn of the Div0 situation and add requirements/errors/validity to cover this situation.

**Comment by SamCooper** [comment]
Requirement added to cope with the DIV0 condition and calculate the delta as +/- max float value. Effectively the result is +/- infinity.
