### ISSUE TITLE
Statistics GetStatistics UNKNOWN error

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#214]
From the description of the UNKNOWN error for functions or parameters, it is not clear whether:
• For a parameter – the parameter does not exist – OR there are no current evaluations which use that parameter
• For a Statistics Function – the function is not supported by the provider – OR there are no current evaluations which use that parameter
Proposed update:  specify UNKNOWN error returned if:
• For a parameter /group– the parameter/group does not exist in the provider
• For a function – the function is not supported by the provider

**Comment by SamCooper** [comment]
Done.
