### ISSUE TITLE
Statistic Link Status

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#215]
- The Statistic High Level Requirements section refers to enable/disable periodic status. This is not consistent with the actual operation name, which is Enable Generation. 
- Also in the description  it is not clear what is meant by the statistics link status. 
- Also the related requirement to continue evaluating the parameter statistics relates to the implementation rather than the service. If the intention is to ensure values are available when generation is enabled – the requirement should be that sampling of parameters continues.

**Comment by SamCooper** [comment]
Sorry this is not clear to me, can you be more definite with the problem is? For example in the high level requirements or in some operation.
Also, the operation is now called eneableReporting.

**Comment by ivandank12** [comment]
For the first point, now there is an **Enable Reporting** operation it is clearer.
For the second point – It is not clear what **‘statistics link status’** is – the term is not used elsewhere. 
For the third point –  high level requirements clause n)b) **–states evaluating the parameter statistics should continue**. How can this be tested if there is no reporting? Why is it necessary?

**Comment by SamCooper** [comment]
So these are all in the high level requirements section?

**Comment by ivandank12** [comment]
Sorry yes

**Comment by ivandank12** [comment]
Only outstanding issue is High level requirement (n) clause - 
b.  continue evaluating the parameter statistics.

It is assumed this should be - stop the evaluation of statistics

**Comment by SamCooper** [comment]
No, it should continue the evaluation, just not report the result. Most likely it is because it will be switch on at a later date.
