### ISSUE TITLE
statistics:monitorStatistics   Definition Id

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#216]
In the statistics:monitorStatistics  operation it states:

**The MAL EntityKey.secondSubKey shall contain the StatisticLink object instance identifier which is the related link of the StatisticValueInstance.**

But in the COM usage section it states:
**The StatisticValueInstance object shall use the related link to indicate which StatisticLinkDefinition object it uses.**

So the issue is should the secondSubKey contain the StatisticLink or StatisticLinkDefinition identifier?

In terms of the EntityKey it is more useful to have the Link Id as it is fixed. However the definition Id should be included in the update – sourceId field?

**Comment by SamCooper** [comment]
Fixed secondSubKey field comment and added related link id to update.
