### ISSUE TITLE
Specification of groups in Statistic operations

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#217]
In the **getStatistics** operation the field which can be used for groups – is of type List::ObjectKey. However in other operations fields (used for groups)  such as **resetEvaluations** the type is  (ListMAL::Long).

It is not clear why different types are used. If the only reason is that these fields can also be used for objects other than groups, a clarification could be included explaining that the domain field is not used where groups are specified.

**Comment by SamCooper** [comment]
The domain field is here because the objects you are referring to at this point may be in a different domain. Whereas the reset evaluations is referring to evaluations that will be in the statistic service domain.
