### ISSUE TITLE
Parameter Service - monitorValue timestamp

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#219]
The COM Archive Service usage section contains the following text:
_When a parameter value report is published, the ParameterValueInstance object should be stored in the COM archive._

The monitorValue description contains the following text:
_The timestamp of the ParameterValueInstance report shall be taken from the publish message and shall be the time of the parameter value creation._

The specification should be updated to clarify if this means :
• the Timestamp is updated each time the report is published – as a ParameterValueInstance object is stored in the archive.
• OR – the timestamp is only updated when the value changes

**Comment by SamCooper** [comment]
It is the former, i.e. the timestamp of the update not any specific value change.
