### ISSUE TITLE
Text clarification

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#22]
I.)   Requirement z) of section 3.5.3 states:

z)  For percentage based delta thresholds, the percentage is calculated as the arithmetic difference between the reference value and the parameter value, as a percentage of the first valid sample where the value 1.0 is 100 per cent. For example, if the reference value is 8 and the parameter value is 14 then the calculation is (14 - 8) / 8 or 0.75 or 75%

The sentence "where the value 1.0 is 100 per cent" is not easy to understand for me, because mavy values are mentioned in the sentence.

Could we not be more explicit ? For instance, could we replace  "where the value 1.0 is 100 per cent" by a sentence like : where a result of the calculation equal to 1.0 is interpreted as 100 per cent

II.) Requirement ff) of section 3.5.3 says:

ff) For a compound check, if the minimumChecksInViolation field is set to '0', the result of the compound check shall be declared successful if any of referenced CheckLink objects is not currently in violation

The sentence "if any of referenced CheckLink objects is not currently in violation" holds a double negation, which makes it difficult to understand. I suggest to turn it in an "affirmative style" like " if no referenced checkLink object is currently in violation"  (provided that I understood correctly what this requirement means)

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
