### ISSUE TITLE
Check Service: There is no way to retrieve the current CheckLinksDefinition object for a CheckLink.

### ISSUE THREAD

**Issue by S-Gaertner** [SamCooper/MC_SPEC_RIDS#220]
It is not possible to retrieve the current CheckLinkDefinition object belonging to a CheckLink.

Querying the archive allows retrieval of all CheckLinkDefinitions, but without a way to determine the current one for a specific CheckLink. Listening for CheckTransition events allows determining the current CheckLinkDefinition for a specific CheckLink, but only if such an event occurs.

I propose to add an additional non-nullable field "linkDefinitionId" of type MAL::Long to the "CheckLinkSummary" structure, which is populated by the operation listCheckLinks.

**Comment by SamCooper** [comment]
Done
