### ISSUE TITLE
Error generated when list different sizes

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#221]
In the specification a number of operations contain a clause specifying an INVALID error shall be raised when two input lists are of a different size. UpdateDefintion in the Alert service is one example of this.

The error description usually has text applicable to more than one error stating:
**a) The extra information field contains a list of the indexes of the erroneous values from the originating list supplied.**

This has been interpreted at the implementation level in different ways so should be clarified (for the size error). Proposed clarification:
**The extra information field will contain the indexes of the elements in the largest list which do not have corresponding elements in the other list .**

**Comment by SamCooper** [comment]
Done.
