### ISSUE TITLE
Check Service interpretation of NominalTime & ViolationTime

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#222]
In the service implementation different interpretations of the definition of nominalTime, nominalCount, violationTime & violationCount have been made which suggests an ambiguity.

• DLR interpretation - As soon as nominalCount valid samples have passed the check evaluation over a nominalTime period I calculate a new CheckResult. This might happen before the nominalTime period has elapsed, because already nominalCount sample have passed the check by then.
• ESA interpretation – at least as nominalCount valid samples have passed the check evaluation over a **minimum** period of nominalTime.  For example if nominalCount valid evaluations are performed in a period less than nominal time, the check evaluation is not updated until (if)  the next valid evaluation is performed later than the minimum period.

The relevant sections of the specification are 3.5.3 t, 3.5.3 v and 4.5.2

**Comment by SamCooper** [comment]
Does #20 help clarify this?

**Comment by ivandank12** [comment]
Well the context does help and suggests the DLR interpretation may be what is required.

But I think the text in 4.5.2 contradicts this:
nominalTime
Duration that a parameter is continuously passing the check for the check to be OK.
violationTime
Duration that a parameter is continuously violating the check for the check to be in violation.

**Comment by SamCooper** [comment]
The desired approach is from the referenced RID, can you work out what needs to change in the requirements to achieve that?

**Comment by ivandank12** [comment]
OK the text in the main part of the document (3.5.3) is consistent with the DLR interpretation. So the proposed solution is to update section 4.5.2, definition of nominalTime and violationTime to make them consistent with 3.5.3. Proposed update for nominalTime:
If nominalCount is zero:
nominalTime is duration that a parameter is continuously passing the check for the check to be OK.
If nominalCount not zero:
nominalTime is the period over which samples will be used in the nominalCount calculation, i.e. sample further in the past than nominalTime are not considered
An equivalent update for Violation time will also be required

**Comment by ivandank12** [comment]
DLR and I have also agreed the following clause should be added to section 3.5.3 (following requirement 'u' )-
if nominalTime is not zero, but nominalCount is zero, a new check result is always calculated (which then has a new timestamp).

and similarly following requirement 'w'
if violationTime is not zero, but violationCount is zero, a new check result is always calculated (which then has a new timestamp).

**Comment by SamCooper** [comment]
Done
