### ISSUE TITLE
Check Service – Check Results Summary timestamp

### ISSUE THREAD

**Issue by ivandank12** [SamCooper/MC_SPEC_RIDS#223]
It is not clear form the specification what value should be used for the **evaluationTime** field in the **CheckResultSummary**.  Specifically if the summary is generated as a result of the maxReportingInterval expiring, should the timestamp be updated at that time, or should it have the value of the time at the last transition?

**Comment by SamCooper** [comment]
The evaluation time in the summary is the time that the last evaluation was made. If that evaluation was as a result of a maxReportingInterval expiring (and the CheckResult prev/current state are therefore the same) then the evaluation time is that of when the maxReportingInterval expired.

**Comment by ivandank12** [comment]
But my understanding is that if the maxReportingInterval expires the last result is reported i.e there is no re-evaluation so I don't see why the timestamp should be updated.

**Comment by SamCooper** [comment]
But it can't be reported as it states that the prev/curr states should be the same

**Comment by ivandank12** [comment]
If maxReportingInterval expires a CheckResult with the current check states shall be generated - 3.5.3 ff

So even if previous and current are the same a report is generated

**Comment by SamCooper** [comment]
Yes, and the timestamp of that CheckResult will be the maxReportingInterval expire time no?

**Comment by ivandank12** [comment]
If that is the intention OK - it is no problem to implement this.

But would it not be more useful if it was the time at which the transition to the current state occurred?

**Comment by SamCooper** [comment]
Probably but it will do for now.

**Comment by SamCooper** [comment]
Done.
