### ISSUE TITLE
Parameter Service : "latest" parameter values returned by the getValue operation 

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#228]
"Latest"  can be interpreted in 2 different ways : either the most recent value of the parameter generated by the on-board system or the actual value of the parameter at the time it is requested. Therefore, the behaviour of the getValue operation should be detailed : does it trigger the generation of a new on- board sample of the requested parameters and then return their values,  like the getStatistics operation behaves, or does it simply return the most recent parameter value generated by the on board system, which in this case would always be a "past" value ?
Please clarify

**Comment by SamCooper** [comment]
latest received
