### ISSUE TITLE
Missing operation inputs checks

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#229]
For the operations that have two imput lists, the service specification usually requires to check that these lists have the same number of entries before carrying out the operation. However, this check is missing in the following operations :
- updateDefinition of the Parameter service
- updateParameterEvaluation of the Statistic service
- updateDefinition of the Aggregation service.

Please consider adding theses checks to these operations.

**Comment by SamCooper** [comment]
Done
