### ISSUE TITLE
Status of the checks when the evaluation of the checks is enabled by the enableService operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#23]
PUS C says that each time the "parameter monitoring function" is enabled, all the checks states of the checks shall be set to "unchecked".

To be consistent with PUS C, this requirement should be added to the enableService operation

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
We have the following requirements now:
- Global check evaluation shall be controlled by the enableService operation.
- Disabling the check service globally shall pause all check evaluations.
- Enabling the check service globally shall resume all check evaluations as they were when they were paused.

Although this is different from PUS C, I think that is OK, as long as we have clearly defined what we do which I believe we have.

Please comment and reopen if you disagree.
