### ISSUE TITLE
Source link of the CheckLink object

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#231]
In the table describing the objects of the check service, thje source link of the CheckLink object is said to be "Parameter :: 1", whereas requirement 3.5.4 g) says that it is the ParameterIdentity object. 

Can you please explain the relation or the equivalence between "Parameter::1" and the ParameterIdentity Object ? Why not use the same terminology in both cases ?

**Comment by SamCooper** [comment]
It is object number '1' of the parameter service which, if you look at the parameter service, is ParameterIdentity.

It is a limitation of the tool I use to generate the tables. I will see if I can fix it.
