### ISSUE TITLE
getSummaryReport operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#234]
1) Section 3.5.9.1 says that "the getSummaryReport operation allows a consumer to obtain the status of a number of **checks definitions** and the result of any check evaluations linked to them". Formally speaking, it seems to me that it is the status of a number of check identities rather than check definitions.

2) Section 3.5.9.2 g) indicates that "The second part shall be the list of all CheckLink details and CheckResults associated with that CheckIdentity"
The CheckResultSummary structure contains the object instance identifier of the check links associated with the checkIdentity but not the CheckLink details.

Please clarify

**Comment by SamCooper** [comment]
Fixed.
