### ISSUE TITLE
triggerCheck operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#236]
1) It should be clarified if the 2 input lists are mandatory or if one or the other can be reduced to "NULL".  

2) 3.5.13.2 g) states that:
 "The two lists shall be combined using 'OR' logic, where a CheckLink is evaluated if the identity of a **link** is in the first list or if the link is directly listed in the second list."
As the 1st list only holds "checkIdentity object instance identifiers", I think the sentence should be:
g) The two lists shall be combined using 'OR' logic, where a CheckLink is evaluated if the identity of a **check** is in the first list or if the link is directly listed in the second list.

Please clarify

**Comment by SamCooper** [comment]
Done
