### ISSUE TITLE
Operations that are ineffective when the status of the check service is disabled

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#24]
The operations of the that are ineffective when the status of the check service is disabled should be indicated in section 3.5.10.2.

In the first instance, I suppose that only the triggerCheck operation will be ineffective

**Comment by SamCooper** [comment]
I'll also add in text to the relevant operations. This is a duplication but a useful one.

**Comment by SamCooper** [comment]
Done.
