### ISSUE TITLE
Check Service: Source link of check links for compound checks shall be NULL

### ISSUE THREAD

**Issue by S-Gaertner** [SamCooper/MC_SPEC_RIDS#253]
The source link of a CheckLink object points to the ParameterIdentity the check is linked to. However, for a compound check it is not clear where the source link should point to.

I recommend to change 3.5.4.g to:

> The CheckLink object shall use the source link to indicate which ParameterIdentity object it is checking. If the CheckLink object belongs to a compound check, the source link shall be set to NULL.

**Comment by SamCooper** [comment]
Done
