### ISSUE TITLE
Some naming issues

### ISSUE THREAD

**Issue by S-Gaertner** [SamCooper/MC_SPEC_RIDS#254]
**Action:updateDefinition**, table in 3.2.13.1: Please change the name `actionDefInstIds` to `actionObjInstIds`, because this field does not contain definition ids but identity ids. This would also be consistent with the naming in Alert::updateDefinition.

**Statistic::updateParameterEvaluation**, table in 3.6.15.1: I propose to rename `objInstIds` to `linkIds` and `newObjInstIds` to `newLinkDefIds`, because the input is a list of StatisticLink object ids, but the output is a list of StatisticLinkDefinition object ids. Using a similar variable name adds confusion.

**Service::addCheck**, 3.5.16.2.b: "`names` field" should read "`checkNames` field".

**Comment by SamCooper** [comment]
Done.
