### ISSUE TITLE
Action Service: Unclear COM ActivityExecution usage behaviour in case of execution failure

### ISSUE THREAD

**Issue by S-Gaertner** [SamCooper/MC_SPEC_RIDS#255]
It is unclear whether all expected activity execution events are also generated in case of an execution failure.

At the moment we assume in our tests that the execution of an Activity stops at the first failure and therefore also stops generating any further activity execution events, even if explicitly requested with `ActionInstanceDetails.stageProgressRequired`, `ActionDefinitionDetails.progressStepCount` and `ActionInstanceDetails.stageCompletedRequired`.

However, this behaviour does not become clear from the specification and I propose to require a different behaviour: It shall be mandatory to generate all expected activity execution events also in case of failure. That is, if `ActionInstanceDetails.stageCompletedRequired` is set to `TRUE` then the completion activity event shall be generated even in case of failure. If `ActionInstanceDetails.stageProgressRequired` is set to `TRUE`, then it shall be mandatory to generate exactly `ActionDefinitionDetails.progressStepCount` events for the progress stages, even in case a step fails.

This behaviour means the consumer can always expect the same number of events, without any exceptions (particularly in case of failure). This also helps failure analysis because if a failure happened and expected events are not generated, this could hint to a data handling or on-board computer problem. If however event generation is suspended after a failure these kind of problems would go unnoticed.

Furthermore, it should be implementation specific whether the activity execution carries on after a step has failed. I can conceive of an Action that is supposed to turn on four heaters in sequence, generating a progress activity event for each of the heaters. An implementation might be such that the remaining heaters are switched on also in case heater number two fails to switch on. In this case I expect all four progress events to be sent, which is not be possible in the current interpretation.

**Comment by SamCooper** [comment]
I think the current behavior is the most desirable as the other stage states can be inferred from the single event and does not waste bandwidth.

I do not agree that an activity behavior should be implementation specific in this sense. I would suggest that an Action defined and implemented like that would be a bad design. Your action should specify that all four heaters shall be attempted and progress reports indicate how many were successfully switch on. 

Everything else we do states that on error execution stops. This should not change here as it would be different to everything else.
