### ISSUE TITLE
Reporting of the "reporting status" of the Statistics

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#27]
There does not seem to be an easy way of obtaining the reporting status of the statistic links. One way could be to add the "reportingEnabled" field to the data structure "StatisticValue", which would enable to obtain the reporting status of the statisticLinks via the getStatistics operation.

Propose an "easy mechanism" to obtain the reporting status of the statisticLinks

**Comment by SamCooper** [comment]
The same issue exists for the check link objects.

I will add an operation to get the enabled state for services that have an enableXXX operation.

**Comment by SamCooper** [comment]
Related to #122

**Comment by SamCooper** [comment]
And also #116

**Comment by SamCooper** [comment]
Will be solved by that RID as it will allow the return of statistic link objects.
