### ISSUE TITLE
Arguments of the resetEvaluation operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#28]
I understand that the input arguments of this operation are either a list of groups of statisticLinks object instance identifiers or a list of StatisticFunction object instance identifiers. This should be made clear either in section 3.6.8.1 or in requirement a) of section 3.6.8.2. As it is now, this requirement does not clearly indicate that the group should hold StatisticLinks object instance identifiers.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
