### ISSUE TITLE
Behaviour of the enableService of the Statistic Service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#29]
I) As well as for the Check service, when the enableService enables the statistical evaluations, all the previous statistical evaluations that were suspended should be resetted before restarting the calculation

II) Detail what the service behaviour should be if the state requested is already the current state of the statistic service

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
