### ISSUE TITLE
Modifying the resetEveryCollection field of the StatisticLink

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#32]
What operation can modify the resetEveryCollection field of the statisticLinks ? It should be possible without removing and re-adding the statisticlinks. Therefore, I suggest to add the capacity of modifying this field to the updateParameterEvaluation.

**Comment by SamCooper** [comment]
updateParameterEvaluation can do this.

**Comment by BEHAL** [comment]
OK, but in that case it should be clearly stated in the section dedicated to this operation. The general section (3.6.14.1) only says that this operation  allows a consumer to modify the intervals for one or more statistical evaluation links. However, the resetEveryCollection field is not an interval.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
