### ISSUE TITLE
filtered AD-HOC aggregation 

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#35]
Requirement j) pf section 3.7.3 says:

j)  If filtering is enabled and a filtered timeout has been set for that aggregation, if no change has been detected in that time-out period, an aggregation value shall be generated with a generation mode of FILTERED_TIMEOUT

This means that an AD-HOC aggregation that is filtered becomes "pseudo-periodic" if no change in the parameters values have overshot the threshold.

Does that make sense ?

**Comment by SamCooper** [comment]
Yes you are correct. That makes sense.

Is there any change to be made as a result of this RID?

**Comment by BEHAL** [comment]
We do not use AD-HOC aggregation at CNES, but my guess would be that when a consumer uses an AD-HOC aggregation, it is because he does not want to receive "periodical" updates but would rather receive "non recurring" results. Therefore, I wonder whether the "filtered" mechanism makes sense for AD-HOC aggregation, because it would imply for the consumer to receive "periodic" results. Filtering seems to make sense only if you receive lots of updates. 
I just want to make sure that this capability has really been asked for in the case of AD-HOC aggregation and that we are not adding "unnecessary" complexity to the standard.

**Comment by SamCooper** [comment]
I will add text to made this clear.

**Comment by SamCooper** [comment]
Done.
