### ISSUE TITLE
COMMON : Typo in the overview section

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#43]
Section 2.1 states :
The Common services are also defined in terms of the COM, as defined in reference [3], and build[s] upon the COM event service and the COM archive.

The s that ends "builds" (in [] in the above sentence) seems to be a typo. If so, remove it please.

**Comment by SamCooper** [comment]
This issue was moved to SamCooper/COMMON_SPEC_RIDS#1
