### ISSUE TITLE
COMMON lookupservice operation : clarification of requirement g) in regard to sessionName

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#46]
Requirement g) of section 3.2.6.2 states :
g) If the sessionName field is the wildcard '*' then all session names shall be matched.

The requirement should be completed and indicate that  all session names "of the requested session type" shall be matched

**Comment by SamCooper** [comment]
This issue was moved to SamCooper/COMMON_SPEC_RIDS#4
