### ISSUE TITLE
COMMON publishservice operation : clarification of requirement b) in regard to publishDetails

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#47]
Requirement b) of section 3.2.7.2 states :
b) For each PublishDetails structure if any of the fields of the domain/session/network fields are either empty or contain the wildcard '*' an INVALID error shall be returned.

Detail if the session refers to the sessionType or the sourceSessionName, or both

**Comment by SamCooper** [comment]
This issue was moved to SamCooper/COMMON_SPEC_RIDS#5
