### ISSUE TITLE
COMMON withdrawservice operation : archive management

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#48]
Requirement f) of section 3.2.8.2 states :
f) The service provider should remove the matched objects from the COM archive

There is no operation to delete an object from the archive. Furthermore, I think that the archive should keep track of all the history of the services. 
Therefore I suggest to discuss this subject inside the group.

**Comment by SamCooper** [comment]
This issue was moved to SamCooper/COMMON_SPEC_RIDS#6
