### ISSUE TITLE
Requirement: 3.7.3.g & 3.7.2.b.c (repeated & consider revision)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#50]
3.7.3.g:
g) Filtered updates for aggregations shall be generated only when the value of one or more parameters in the aggregation has changed by more than a given threshold since the previous generation or when the filtered timeout expires.

This requirement is repeated twice: 3.7.3.g & 3.7.2.b.c
The requirement is ambiguous. Please consider splitting it into 2 requirements.  The last 'or' can be misinterpreted.

**Comment by CesarCoelho** [comment]
You can see the last OR in 2 different ways:

1.
Filtered updates for aggregations shall be generated (only when the value of one or more parameters in the aggregation has changed by more than a given threshold since the previous generation) or (when the filtered timeout expires).

2.
Filtered updates for aggregations shall be generated only when the value of one or more parameters in the aggregation has changed by (more than a given threshold since the previous generation) or (when the filtered timeout expires).

This requirement should not be ambiguous. My suggestion above was to split it in 2.

**Comment by SamCooper** [comment]
Done
