### ISSUE TITLE
ParameterValue isValid field redundant?

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#51]
I was checking the new ParameterValue structure and isn't:
isValid = (invalidSubState.getValue() == 0);     ??

Do we really need to keep sending the isValid Boolean on the line?
If it can be deduced from the invalidSubState with a simple line of code then it is redundant.
Do we really need to have it? Aren't we just increasing the traffic with redundant information?

Sam's Answer: They are both good points, can you raise RIDs on them please.

**Comment by SamCooper** [comment]
Done
