### ISSUE TITLE
Keep Validity enumeration matching the written definitions of the invalidSubState field

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#52]
Is it possible to keep the Validity enumeration numerical values to match the written definitions? On a previous question you said that the invalidSubState will no longer be represented by the Validity enumeration. But I guess that the Validity enumeration could still be there matching the different states and also it should be possible to use it by someone interested, no?
For example, in my code for the demo I am currently doing (provider):
Validity validity = generateValidityState(PDeflist.get(index), (convertedValue != null) );
UOctet invalidSubState = new UOctet((short) validity.getNumericValue().getValue());

And on the consumer side I do the opposite, this is, I generate the Validity object from the invalidSubState.

**Comment by SamCooper** [comment]
Done
