### ISSUE TITLE
Re-load of deleted Definitions upon service restart

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#53]
Currently, on a service restart, there's the possibility that deleted Definitions might be loaded again. This should never be possible therefore, is worth a mention on the book.
Suggestion:
Include a simple line of text on every "General" Section of each Service stating that previously deleted Definitions shall not be loaded upon service start-up (even if they still exist in the Archive).

**Comment by SamCooper** [comment]
I'm not sure that would be right though, I'm not sure we can state that.

Think of the situation where I want the provider to resume from a previously known good state when starting up, so that any changes I make are temporary. Putting that requirement in would make me non-compliant.

**Comment by SamCooper** [comment]
This approach is delegated to the Configuration service.

Closed.
