### ISSUE TITLE
M&C - Setting a parameter value (mechanisms)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#56]
In section 2.1 (Overview General), it does not mention the mechanism of control by setting a parameter:
"The M&C services provide operations for generic monitoring and control of a remote service
provider (e.g., a spacecraft or ground system component) in terms of three fundamental
mechanisms and associated data items:
– action invocation—actions;
– parameter status—monitoring parameters;
– alert notification—alerts."

Same on section 2.2:
"Parameters provide status monitoring capability."

**Comment by SamCooper** [comment]
Done.
