### ISSUE TITLE
setValue operation: Read-only parameters must return an error

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#59]
I believe that there are some parameters that are not "settable", for example, the temperature of some instrument in the spacecraft. 
So, maybe you need to add another error saying "You cannot set parameter X". 

I think that  a good example could be a temperature regulator, So: "You can set the desired temperature for a certain instrument, but you cannot change (set) the real temperature values that are being measured."

Sam's answer:
"Well you can in a simulated environment but I get what you mean in terms of read-only parameters. The question is what error to return, an existing one or a specific. Looking at what is currently defined for setValue it looks like a specific read only error should be raised. Can you raise a RID on this please."

**Comment by SamCooper** [comment]
Done.
