### ISSUE TITLE
ConditionalReference object: Calculation of the convertedValue

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#62]
It was not clear to me how to calculate the convertedValue from the ConditionalReference object.

The email exchange follows:

---

Hi Sam, 

I am implementing the conversion service and there's something not clear in the M&C book: What happens when one condition in the ConditionalReference object evaluates to false? 
Should the converted value be null or equal to the rawValue? 
(I am considering only one condition in the conversionConditions in he ParameterDefinition) 

Now, considering that I have multiple conditions (4 conversionConditions), which one would be the behaviour: 

Where: (input = 1) 
Below you have: "step. Evaluation result (conversion entity) -> output" 

---

First: 
1. True (multiply by 5) -> 5 
2. False (sum 1) -> 5 
3. True (multiply by 2) -> 10 
4. True (sum 2) -> 12 

---

OR 

---

Second: 
1. True (multiply by 5) -> 5 
2. False (sum 1) -> null 
3. True (multiply by 2) -> null 
4. True (sum 2) -> null 

---

I believe that this should be clear in the standard. May I raise a RID to write in the ConditionalReference object what is the output if the evaluation of the condition is false? 

Best regards, 
César Coelho 

---

---

The conditional conversions are a list of conversions that get applied if their condition is true. Once you have a conversion you stop, you don’t bother to evaluate the others.

They are often used to allow different calibrations depending on whether the equipment is on the bench at ESTEC or bolted to the side of the spacecraft in space.

---

---

 oh, ok

I was not expecting that...

So you are saying that in my example below, the output would be:

---
1. True (multiply by 5) -> 5 

---

Best regards,
César Coelho

---

Please clarify this process in the ConditionalReference object or in the Conversion service requirements. Maybe this info can be in both places.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
