### ISSUE TITLE
requirement: 3.2.9.3.1 (Error: INVALID)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#65]
"
a)  The argument list contains one or more invalid arguments.
b)  The extra information field contains a list of the indexes of the erroneous values from the originating list supplied.
"
The error assumes a List in the arguments of the operation. This does not correspond to the truth. Either change the arguments to a list or fix the text in this error.

**Comment by SamCooper** [comment]
It is the arguments of the submitted action rather than the arguments of the submitAction operation. 

I have updated the error description to reflect that.
