### ISSUE TITLE
3.3.2.a Parameter Service - High Level Requirements

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#66]
"
a)  The parameter service shall provide:
a.  the capability for periodic reporting of predefined parameter values;
b.  the capability for requesting the current value of a set of parameters;
c.  the capability for controlling reporting of the parameter values;
d.  the capability for maintaining the list of parameter definitions.
"

Between point b and c, there's one capability missing:
x.  the capability for setting the raw parameter value of a set of parameters;

**Comment by SamCooper** [comment]
Done.
