### ISSUE TITLE
Group Service (groups of groups: possibility for infinite loop)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#67]
"It is also possible to define a group of groups, where one group holds links to other groups which in turn either contain groups or other objects. All operations that support groups also support this concept of groups of groups however the objects that they finally link to must still all be the same type and be supported by the specific operation. For example, if an operation states that it can reference objects of type X or groups of X then it must also support groups of groups of X. The depth of the grouping is not limited by this specification"

Let's consider the following situation: Group X holds a link to Group Y AND Group Y holds a link to Group X. An infinite loop will occur and lock the code:
X->Y->X->Y->X->Y->X->Y->X->Y->...

One extra requirement should be added to avoid this situation.

**Comment by SamCooper** [comment]
I'm not sure we can add this as a requirement, how would you implement that requirement as groups are maintained via the Archive service which does not do any checking. We can add it is advisory text though.

**Comment by SamCooper** [comment]
Done as a comment.
