### ISSUE TITLE
Group Service (groups of groups with different types)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#70]
"A group of (groups with different object types), shall not be possible."

This should be one of the the requirements.
Please feel free to reformulate the requirement without creating ambiguities.
Maybe it should also say that groups of groups are ok. (because Group has its own object type)
Perhaps:
"All the objects within the group of groups must have the same object type."

**Comment by SamCooper** [comment]
Done as a comment in the overview text.
