### ISSUE TITLE
Action Service (when less is more)

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#71]
There are too many requirements and some are repeated:
For example:
3.2.2.d:
"The action service shall use the COM Activity Tracking service to report the execution progress of a submitted action."
and
3.2.8.a:
"The COM Activity service should be used to monitor the transfer and execution of the submitAction operation."
3.2.3.a:
"The COM activity tracking service shall be used to report the transport and execution progress of the submitAction operation"
3.2.5.a:
"Execution progress of an activity shall be reported using COM ActivityTracking Execution events."

---

Please review these sections (3.2.2 to 3.2.8) and avoid repeating requirements.

**Comment by SamCooper** [comment]
3.2.2.d and 3.2.3.a removed.

Closed
