### ISSUE TITLE
Remnant requirement: 3.4.2.c

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#73]
In the High Level Requirements of the Alert service:
"
c)  It shall be possible to report the alert enabled/disabled status.
"

I believe that this is part of some old operation which is no longer in use because to check the enabled status, one must retrieve the corresponding Alert definition and check the field.
Please remove the requirement above.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
