### ISSUE TITLE
Action Service: ActionDefinitionDetails & ActionInstanceDetails

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#74]
The arguments field of the ActionDefinitionDetails structure is not nullable.

The argumentValues of the ActionInstanceDetails structure is nullable and contains in the description: "The ordering of the list matches that of the definition. If a value for a particular entry is not being supplied, then its position is filled with a NULL value. If no arguments are defined, then the complete list is replaced with a NULL."

As these two fields need to be matched in the provider side, it would be good to have either both fields nullable or none nullable.
I would suggest to have both nullable and add the following comment on the argument field of the ActionDefinitionDetails: "If no arguments are defined, then the complete list is replaced with a NULL."

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
