### ISSUE TITLE
Behaviour of the ListDefinition operations

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#78]
In all the services that are using it, it is said that the listDefinition operation allows a consumer to request the object instance identifiers of the "xxxIdentity" and "xxxDefinition" (e.g; ActionIdentity and ActionDefinition) objects. 

It is now possible to create several "definitions" for the same "identity". As the operation is used in conjunction with the COM archive, will it provide for each "identity" all the existing "definitions" stored in the archive ?

The behaviour of the ListDefinition operation should be more detailed.

**Comment by SamCooper** [comment]
It will return the definition that is being used currently by the provider.

I will clarify this.

**Comment by SamCooper** [comment]
Done.
