### ISSUE TITLE
Errors returned by the listDefinition operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#79]
It is said that this operation does not return any error.

What happens if the supplied actionNames are unknown, NULL or empty ?

I suggest to describe the listDefinition behaviour in these cases and to add errors (Unknow, Invalid).

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Duplicate of #11 

Will be closed by that RID
