### ISSUE TITLE
Name of the objects in the action service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#8]
Replace "action definition " by "ActionDefinition" and "action instance" by "ActionInstance" in the following sentences of paragraph 3.2.1:
   The action service defines two types of objects, the first type is the action definition  object that holds the description of an action with the list of required/optional arguments. The second type is the action instance  object that holds details of a specific action instance namely a value for each of the arguments of the action.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
