### ISSUE TITLE
Action service : errors description of the addDefinition operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#81]
Please, consider enhancing the following requirements (adding extra words between quotes"):
section 3.2.12.3.1
  a)  One of the supplied "actionIdentity objects" contains an invalid action name

section 3.2.12.3.2
  a)  One or more of the "actionIdentity objects" being added has supplied an action name that is already in use in the domain

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
