### ISSUE TITLE
updateDefinition operation overview

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#82]
In all the services that are using the updateDefinition, the general section states:

```
"The operation must not be used to change the name of an existing XXX, removal of the existing XXX and adding the new definition must be used in this case"
```

The input data structures currently used by the updateDefinition operation do not contain anymore the name of the "object", therefore, this operation cannot change ithe object name and the above sentence as it is does not make sense.

I suggest to replace it in all the services by something like:

   "To change the name of an existing XXX Identity, removal of the existing XXX Identity with the removeDefinition operation and adding the new definition with the addDefinition operation must be used in this case"

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I have removed the text from the operations as it makes no sense any more.
