### ISSUE TITLE
RemoveDefinition operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#84]
If my understanding is correct, the removeDefinition operation currently removes all the definitions of an "Identity" and does not allow anymore to remove a specific definition or a subset of definitions. Its behaviour is different from what it used to be in the previous versions of the MC services.

Yet, I think that there is still a need to be able to remove only a specific subset of definitions.

I suggest to discuss this matter in the working group and if need be, to add a new operation.

**Comment by CesarCoelho** [comment]
WG review:

The name of the operation is misleading, consider change.
Update text and operation specificatino to reflect the true nature of the operation.

**Comment by SamCooper** [comment]
Related to #137

**Comment by SamCooper** [comment]
Description has been updated.

**Comment by BEHAL** [comment]
The proposed solution does not seem to answer my question : I was asking for an operation to remove a subset of definitions. If my understanding of your answer to # 137 is correct, you say that all the définitions associated to an identity are removed with the identity.

**Comment by SamCooper** [comment]
WG review: 
Change operation name to be something like removeParameter (and also maybe change addDefinition to addParameter).
Make clear the required behaviour when removing a parameter (and associated Identity and Definitions) and then readding the same parameter (samd identity). The previous Identity should be reused.

**Comment by SamCooper** [comment]
Done
