### ISSUE TITLE
EnableGeneration operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#88]
This operation is in particular used by the Parameter service, the Alert service and the Aggregation service.
In these 3 cases, it is said that:
  "a)   If the isGroupIds field is TRUE then the enableInstances field shall contain Group object instance identifiers, otherwise the field contains  xxxIdentity object instance identifiers"

As there can be many definition objects associated with an identity objects, how does this operation behave ? Does it enable all the definitions associated with the identity object? 

If so, this behaviour is different from the previous versions of the MC services where the consumer could control a specific subset of object definitions.

I think the need to control specific definitions or subsets of definitions still exists. 

I suggest to discuss this matter with the SMC WG and if needed, to modify the EnableGeneration operation

**Comment by SamCooper** [comment]
Accepted

**Comment by CesarCoelho** [comment]
WG review:

Update text to clarify the behaviour of the operation.
Make it clear that there is only one active definition.

**Comment by SamCooper** [comment]
Done.
