### ISSUE TITLE
Service Alert : updateDefinition

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#89]
It is said in the general section 3.4.11.1 that:

   "This differs from deleting an existing alert and adding a new definition with the same alert name in the fact that the ParameterIdentity object is not changed between the two definitions"

I think it is rather the AlertIdentity object than the ParameterIdentity object

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Done.
