### ISSUE TITLE
Object number of the ActionFailure event

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#9]
The number given to the ActionFailure event is 3. It is the same number as the Forward activity transfer event. In a case where there is a relay between the SCC and the spacecraft, both events could be used. 

Would it not be better to use another number for the ActionFailure event ? For instance 6 ?

**Comment by SamCooper** [comment]
The object number is combined with the area and service numbers so there is actually no overlap.

However, if it might help in clarity I can make this change.

Let me know what you think?

**Comment by BEHAL** [comment]
Please change the ActionFailure event number, even though there is no risk of overlap. At first sight, it can be confusing as it is now.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
