### ISSUE TITLE
Controls performed by the updateOperation of the Alert Service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#90]
Requirement f) of section 3.4.11.2 says:

   "f)  If the lists are not the same size an INVALID error shall be returned."

This requirement seems to refer on one hand to the list of the object instance identifiers of the AlertIdentity objects to be updated, and on the other hand to the list of AlertDefinitionDetails. 

As the AlertDefinitionDetails is a structure composed of several fields, whereas the object instance identifier holds a unique field, what do you mean when you say that the lists must have the same size ?

That they must have the same number of entries ?

Why is this control only performed in the Alert service ?

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Done.
