### ISSUE TITLE
Controls performed by the addDefinition operation of the chech service Service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#91]
Requirement f) of section 3.5.15.2 says:

  "f) The two lists shall be the same size otheriwse an INVALID error shall be raised."

This requirement seems to refer on one hand to the list of check names, and on the other hand to the list of CheckDefinitionDetails.

As the checkDefinitionDetails is a structure composed of several fields, whereas the check name holds a unique field, what do you mean when you say that the lists must have the same size ?

That they must have the same number of entries ?

Please clarify

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done.
