### ISSUE TITLE
Service Parameter : potential impacts of the updateDefinition operation behaviour on the checklink objects

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#92]
As the updateDefinition operation generates a new definition object, it implies that each time the generation of  parameter updates is enabled or disabled, or the update interval of a parameter is modified, a new definition of this parameter will be created. Therefore, the checklink object related to the previous parameter definition will have to be removed and recreated.

I think that it should at least be clearly emphasized in the general section of this operation and also discussed with the group, because up to now, the enabling/disabling of parameter updates generation did not impact the checklink objects, same for the updateInterval modification.

**Comment by SamCooper** [comment]
Accepted.

**Comment by CesarCoelho** [comment]
WG review:

Review the consistency of the relationships between the service objects and review the effects of the operations may have on each other, specifically changes to one object definition needing to be reflected in other object definitions.

**Comment by SamCooper** [comment]
Related to #179

**Comment by SamCooper** [comment]
Closed by closing of #179 

Specifically the check link object now "links" to the ParameterIdentity object rather than the definition.
