### ISSUE TITLE
addParameterEvaluation operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#93]
Requirement d) of section 3.6.13.2 says:

   "d)  The parameterId shall reference the ParameterIdentity that the function is being applied to."

In the current version of the MC services, several parameterdefinition objects can be related to a parameterIdentity. 

How can the provider backtrack to the parameterDefinition that the consumer wants to evaluate ?

**Comment by SamCooper** [comment]
This needs a review.

**Comment by SamCooper** [comment]
Related to #179

**Comment by SamCooper** [comment]
Closed by the closing of #179 

Specifically, there is only one ParameterDefiniton in effect at any one time, the current definition, so referencing the parameter identity means "use current definition". The StatisticValue structure now contains an extra field to provide the definition used for the statistical evaluation.
