### ISSUE TITLE
EnableFilter

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#94]
Requirement a) of section 3.7.10.2 says:

  "a)   If the isGroupIds field is TRUE then the enableInstances field shall contain Group object instance identifiers, otherwise the field contains AggregationIdentity object instance identifiers."

As there can be several aggregationDefinitions related to an AggregationIdentity, can you please clarify the behaviour of the operation ?

I think the need to filter a specific subset of aggregationDefinitions still exist and should be discussed in the SMC WG

**Comment by CesarCoelho** [comment]
WG review:

Update text and operation specification to reflect the true nature of the operation.
Make it clear that there can only be one active definition (maybe do in section 2) and that is the one affected by this operation.

**Comment by SamCooper** [comment]
Done.
