### ISSUE TITLE
ParameterExpression

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#97]
As a consequence of the new data model, enabling / disabling the generation of parameter updates or modifying parameter update interval will also have an impact on parameterExpressions.

It should be emphasized somewhere in the book.

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Fixed, parameter expression now points to ParameterIdentity so the cascade update does not happen.
