### ISSUE TITLE
listDefinition operations

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#98]
Usually there's a requirement saying:
"The returned list shall maintain the same order as the submitted list unless the wildcard value was included in the request"

What happens if one of the entries in the submitted list doesn't match any definition? Either should return an error or be replaced with a null. Please clarify this in every listDefinition as it should not be open to interpretation.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
Done
