### ISSUE TITLE
Action Service: preCheckAction

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/MC_SPEC_RIDS#99]
Error: Invalid
This error doesn't apply in this operation. Please remove it or fix it because:
" The argument list contains one or more invalid arguments."
This is too abstract. 
I am assuming that this error is returned when the comparison of the argumentIds field from the ActionInstanceDetails structure with the argumentIds field from the ActionDefinitionDetails.

Please add solid requirements stating that this comparison must be done. Before that, I would additionally add a requirement to compare the list sizes of both fields. These fields are optional, therefore include also in the requirement that they can be both null, etc...

There's also another question: In the arguments field of the ActionDefinitionDetails structure, one can define the details of an argument definition with a set of associated attributes. For example, considering that I select a string in the rawType field, is this field being compared with the submitted value of the argumentValues of the ActionInstanceDetails? The argumentValues is type List<AttributeValue>, which contains simply a MAL::Attribute. In no part of the Action service requirements, there's a mention to a comparison of these two values! Please add a requirement clearly stating that the submitted value Attribute Short Form Part must be the same as the one declared in the arguments field of the ActionDefinitionDetails structure. I suggest to put it on the preCheckAction operation but on the Functional Requirements section wouldn't be such a bad option either.

Remember that all the requirements in the preCheckAction must be on the submitAction operation. It might be easier to just point to the requirements from the preCheckAction operation. Example: "All the requirements of the preCheckAction operation (from a.b.c to x.y.z) are valid and must be met for the submitAction operation."

**Comment by SamCooper** [comment]
Accepted.

**Comment by SamCooper** [comment]
Done.
